paketo-buildpacks/github-config

- language-family/.mergify/config.yml
- These are the PRs created by github actions when
new implementation buildpacks are released
Co-authored-by: Arjun Sreedharan <asreedharan@vmware.com>
Relates to https://github.com/paketo-buildpacks/nodejs/issues/1
> Use mergify app to auto-merge PRs in lang family

- actions/dispatch/action.yml
- implementation/workflows/send-dependency-update.yml
Fixing callers of dispatch due to change in #9
> Update repo references in dispatch action

- language-family/scripts/package.sh
- creates a .cnb artifact from a buildpacks buildpack.toml file.
> language family package.sh script

- language-family/workflows/create-release.yml
- releases include a summary of the contents of the language family
buildpack
- release artifact is a .cnb file
> Adds the workflow for creating a language-family release

- actions/dependency/update/entrypoint/main.go
- actions/dependency/update/entrypoint/main_test.go
> The dependency/update action updates order groups

- implementation/scripts/.util/git.sh
- implementation/scripts/.util/print.sh
- implementation/scripts/.util/tools.sh
- implementation/scripts/build.sh
- implementation/scripts/integration.sh
- implementation/scripts/package.sh
- implementation/scripts/unit.sh
- no longer pulling latest pack or jam, these are now hardcoded to a
specific version
> Adds implementation/scripts directory

- .github/workflows/test-pull-request.yml
- scripts/sanity.sh
> Wire repo check to run on PR

- actions/sync/Dockerfile
- actions/sync/action.yml
- actions/sync/entrypoint
- implementation/.github/workflows/receive-github-config-updates.yml
- triggers on a repository dispatch
- creates a pr with updates from specified directory
Co-authored-by: Josh Zarrabi <jzarrabi@pivotal.io>
> adds sync action

- actions/sync/entrypoint
> add all files when syncing

- implementation/scripts/integration.sh
- language-family/.github/workflows/create-draft-release.yml
- resolve tooling script issue
- include reset-draft action in language-family release workflow
- creates language-family releases as drafts
> Fix auto-update workflow issues

- implementation/.github/workflows/create-release.yml
- implementation/.github/workflows/send-dependency-update.yml
- implementation/.github/workflows/test-pull-request.yml
- language-family/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/update-buildpack-toml.yml
> Uses the PAKETO_BOT_GITHUB_TOKEN so that actions are triggered

- language-family/.github/workflows/create-draft-release.yml
> Fixes a typo in the asset JSON for language-family releases

- language-family/.github/workflows/create-draft-release.yml
> Uses a relative path so that we can find the asset

- language-family/.github/workflows/update-buildpack-toml.yml
> Fixes the branch for pulling the dependency update action

- language-family/.github/workflows/update-buildpack-toml.yml
> Adds ssh key when pushing dependency update

- actions/tag/entrypoint
- implementation/.github/workflows/create-release.yml
- implementation/.github/workflows/test-pull-request.yml
- implementation/scripts/package.sh
> Adds safe defaults when a cnb repo doesn't have any tags

- implementation/scripts/integration.sh
- language-family/scripts/integration.sh
- makes GOMAXPROCS configurable
- enforces count=1 so that cache is disabled
> Improves scripts/integration.sh for implementation and language-families

- language-family/.github/workflows/update-buildpack-toml.yml
This is helpful when you are looking at a list of PRs.
> Include version in dependency update PR title

- .github/data/implementation-cnbs
- actions/sync/action.yml
- actions/sync/entrypoint
Signed-off-by: Daniel Thornton <dthornton@vmware.com>
> allow the sync action to work with bootstrapper

- actions/sync/Dockerfile
- actions/sync/action.yml
- actions/sync/entrypoint
- implementation/.github/workflows/receive-github-config-updates.yml
- language-family/.github/workflows/receive-github-config-updates.yml
The current sync action implementation opens a new PR every time there is a new commit on master. This implementation will use a stable branch when it opens PRs so that the branch can be updated on subsequent changes and the PR will get updated if it is still open.
> Updates sync action to use a stable branch

- actions/buildpackage/download/entrypoint
- language-family/.github/workflows/push-buildpackage.yml
> Uses API endpoint to download buildpackage

- actions/dependency/update/entrypoint/main.go
- actions/dependency/update/entrypoint/main_test.go
> add support for updating package.toml files

- actions/dependency/parse/action.yml
- actions/dependency/parse/entrypoint/main.go
- actions/dependency/parse/entrypoint/main_test.go
- implementation/.github/workflows/send-dependency-update.yml
- handles private repos and multiple assets on a release
> Updates send-dependency-update workflow and dependency/parse action

- actions/dependency/parse/entrypoint/main.go
- actions/dependency/parse/entrypoint/main_test.go
> Fix dispatched URI's to be downloadable without token

- implementation/.github/workflows/create-release.yml
- implementation/.github/workflows/push-buildpackage.yml
- implementation/scripts/.util/tools.sh
- implementation/scripts/package.sh
- released buildpackages will be pushed to GCR
> Releases will include buildpackage artifacts

- .github/data/implementation-cnbs
Signed-off-by: Tim Hitchener <thitchener@pivotal.io>
> Update go-mod reference to go-mod-vendor

- actions/dependency/update/entrypoint/main.go
- actions/dependency/update/entrypoint/main_test.go
- matching on prefix caused errors
> look for exact string match in dependency update for language famolies

- implementation/scripts/.util/tools.sh
- implementation/scripts/integration.sh
- implementation/scripts/package.sh
- language-family/scripts/.util/tools.sh
- language-family/scripts/integration.sh
- language-family/scripts/package.sh
- jam updated to v0.2.4
- pack updated to v0.12.0
- integration script now inspects the builder to pull run-image and
lifecycle
> Updates tools and builder image references

- language-family/.github/workflows/update-buildpack-toml.yml
> Dependency updates add to existing PRs

- actions/pull-request/approve/entrypoint
- implementation/.github/workflows/test-pull-request.yml
- implementation/.mergify/config.yml
- language-family/.github/workflows/test-pull-request.yml
- language-family/.mergify/config.yml
- uses a new paketo-bot-reviewer account to do auto-approve
- adds paketo-bot PRs to mergify rules
> Allows paketo-bot PRs to be auto-merged

- implementation/.github/workflows/receive-github-config-updates.yml
- language-family/.github/workflows/receive-github-config-updates.yml
"Sync" is a little difficult to understand when reading
the actions pane of a cnb repo
> workflow: s/Sync/Handle dispatch from github-config

- .github/workflows/notify-implementation.yml
- .github/workflows/notify-language-family.yml
- .github/workflows/test-pull-request.yml
- actions/release/create/action.yml
- actions/sync/action.yml
- actions/sync/entrypoint
- implementation/.github/workflows/create-release.yml
- implementation/.github/workflows/lint.yml
- implementation/.github/workflows/push-buildpackage.yml
- implementation/.github/workflows/receive-github-config-updates.yml
- implementation/.github/workflows/send-dependency-update.yml
- implementation/.github/workflows/test-pull-request.yml
- language-family/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/lint.yml
- language-family/.github/workflows/push-buildpackage.yml
- language-family/.github/workflows/receive-github-config-updates.yml
- language-family/.github/workflows/test-pull-request.yml
- language-family/.github/workflows/update-buildpack-toml.yml
Signed-off-by: Sophie Wigmore <swigmore@vmware.com>
> Use main branch instead of master

- scripts/clone-all-repos.sh
Signed-off-by: Josh Zarrabi <jzarrabi@vmware.com>
> adds script to clone all repos

- actions/release/notes/Dockerfile
- implementation/scripts/.util/tools.sh
- language-family/scripts/.util/tools.sh
Co-authored-by: Forest Eckhardt <feckhardt@pivotal.io>
Co-authored-by: Sophie Wigmore <swigmore@vmware.com>
> Bump version jam version to 0.2.5 to get new jam summarize output

- .github/data/implementation-cnbs
Co-authored-by: Frankie Gallina-Jones <frankieg@vmware.com>
> Adds paketo-community/rake to list of implementation buildpacks

- implementation/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/create-draft-release.yml
- reset language-family draft right before recreate
> Implementation releases should be drafts

- .github/data/implementation-cnbs
> add node-start to list of implementation cnbs

- implementation/.github/workflows/auto-merge.yml
- language-family/.github/workflows/auto-merge.yml
This simplifies the workflow into a single job instead of 3. It allows us to remove some duplicated steps, and speed up the process a bit.
> Simplifies automerge workflows

- implementation/scripts/.util/git.sh
- implementation/scripts/.util/tools.sh
- implementation/scripts/build.sh
- implementation/scripts/integration.sh
- implementation/scripts/package.sh
- implementation/scripts/unit.sh
- language-family/scripts/.util/tools.sh
- language-family/scripts/integration.sh
- language-family/scripts/package.sh
- scripts/.util/print.sh
- scripts/bootstrap.sh
- scripts/clone-all-repos.sh
- scripts/repo_rules.sh
- scripts/sanity.sh
- scripts/unit.sh
> Adds usage to all scripts

- actions/pull-request/create-commit/entrypoint
This was causing CLA to fail since the user that signed the CLA
is paketo-bot <paketobuildpacks@gmail.com>
See lastpass/paketo.yml to verify email addr
> Fix paketo-bot's email address

- implementation/scripts/build.sh
Reduces binary size by 30-50% in most cases.
> Uses upx to compress built binaries if upx is installed

- actions/release/notes/Dockerfile
- implementation/scripts/.util/tools.sh
- language-family/scripts/.util/tools.sh
Signed-off-by: Sophie Wigmore <swigmore@vmware.com>
> update jam version to v0.3.0

- README.md
> Removes mergify details from README

- implementation/scripts/build.sh
> Removes upx

- implementation/.github/workflows/update-github-config.yml
- language-family/.github/workflows/update-github-config.yml
Following the implementation of updating dependencies on a schedule that was developed in the builder repos, this changes the updating of the shared github-config to a scheduled workflow.
> Updates github-config on a schedule

- implementation/.github/workflows/lint.yml
- language-family/.github/workflows/lint.yml
Updates the linter action to the latest version
Fixes the linting workflow for PRs
> Bumps the lint action to the latest versions

- actions/buildpack/update/Dockerfile
- actions/release/notes/Dockerfile
- implementation/scripts/.util/tools.sh
- language-family/scripts/.util/tools.sh
Updates `jam` to v0.4.2.
Please confirm the following:
> Updates jam to v0.4.2

- implementation/.github/workflows/push-buildpackage.yml
- language-family/.github/workflows/push-buildpackage.yml
Implements [RFC0015](https://github.com/paketo-buildpacks/rfcs/blob/main/accepted/0015-dockerhub-distribution.md)
> Images are also pushed to DockerHub

- implementation/scripts/integration.sh
Co-authored-by: Josh Zarrabi <jzarrabi@vmware.com>
Relies on https://github.com/ForestEckhardt/freezer/pull/5 being included in the buildpack
> only fetch github token for integration tests if a flag is passed

- implementation/.github/workflows/push-buildpackage.yml
- language-family/.github/workflows/push-buildpackage.yml
Resolves #204
See POC:
https://github.com/paketo-buildpacks/nginx/blob/v0.0.199/.github/workflows/push-buildpackage.yml#L36-L57 => https://github.com/paketo-buildpacks/nginx/runs/1825813921?check_suite_focus=true#step:8:1 => https://github.com/buildpacks/registry-index/blob/main/ng/in/paketo-buildpacks_nginx
> Push buildpackage: Register with CNB registry as well

- actions/sync/action.yml
- actions/sync/entrypoint
- implementation/.github/workflows/update-github-config.yml
- language-family/.github/workflows/update-github-config.yml
This reverts commit 1a2a9f462ca4b78a3310652ec1752de78618fb9c.
This previous PR was created incorrectly. Because the PR impacts the syncing action itself, it needs to be broken up into 2 pieces. The current syncing functionality across all repos is broken, so this PR reverts that commit to bring everything back to its original state. I will then submit 2 different PRs that can be merged to enable this to get rolled out correctly.
> Revert "Refactors sync action to only perform rsync"

- builder/.github/workflows/update-github-config.yml
- implementation/.github/workflows/update-github-config.yml
- language-family/.github/workflows/update-github-config.yml
Updates the sync workflow for builders, implementations, and language families to use the new sync action (on a separate branch for now). Once this lands everywhere, I can open another PR that updates this action on main and each of the references in the workflows.
This is already working on [go-generate](https://github.com/paketo-community/go-generate/runs/1938721867?check_suite_focus=true).
> Sync workflow

- implementation/.github/workflows/update-github-config.yml
Using this token will let us commit this successfully when we modify the workflows directory.
> We have to use our bot token to checkout

- builder/.github/workflows/update-github-config.yml
- language-family/.github/workflows/update-github-config.yml
Makes the same change as https://github.com/paketo-buildpacks/github-config/pull/233, but for builders and language families.
> Updates other workflows to use token when checking out repo

- implementation/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/create-draft-release.yml
> Add manual trigger for draft release workflow

- .github/workflows/test-pull-request.yml
- builder/.github/workflows/create-release.yml
- builder/.github/workflows/test-pull-request.yml
- implementation/.github/workflows/create-draft-release.yml
- implementation/.github/workflows/test-pull-request.yml
- language-family/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/test-pull-request.yml
We had been using 1.14 in some cases, and 1.15 in others. 1.16 is the latest.
> Bumps all action workflow Go version to 1.16

- actions/sync/Dockerfile
- actions/sync/action.yml
- actions/sync/entrypoint
- builder/.github/workflows/update-github-config.yml
- implementation/.github/workflows/update-github-config.yml
- language-family/.github/workflows/update-github-config.yml
Now that all of the existing workflows that used the old sync action have been updated to use the new one (#232, #233, #234, and #236), we can update the action on the `main` branch with the newer, simpler implementation. This PR also updates all references in workflows to point at the `main` branch for this action instead of the placeholder `sync-action` branch. Once we have completed moving all repos onto the `main` branch action, we can remove the `sync-action` branch.
> Update sync action

- implementation/.github/workflows/codeql-analysis.yml
After a [successful experience with CodeQL on `packit`](https://github.com/paketo-buildpacks/packit/security/code-scanning), I think we should include it on all of our repos to give us some feedback about any security vulnerabilities we may have in our code.
> Adds CodeQL analysis workflow to all implementation repos

- actions/release/notes/Dockerfile
- actions/release/notes/action.yml
- actions/release/notes/entrypoint
- implementation/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/create-draft-release.yml
The changelog added here is just a first-pass at something that can involve into a more useful solution. We haven't solidified our use of labels on issues/PRs yet, and so we aren't really in a state to use them to group changelog output yet. Once we do that, it makes sense to start to group these changes. That being said, including something now is better than doing nothing until we come to a consensus.
The output will look like this:
Resolves #259
> Adds very basic changelog to release notes

- actions/release/notes/entrypoint
In the case where the repo has not made any releases yet, we don't need a changelog.
> Handle release notes for repos that have not released yet

- scripts/clone-all-repos.sh
I noticed that the source of truth for the repos cloned by the `clone-all-repos.sh` script was prone to fall out of date. Updated the script to clone all of the repos in the Paketo project that have maintainer teams (except Java ones). The script can therefore be used to clone new repos as they're added to the project without further updates.
> use Github Teams to determine repos to clone

- scripts/.util/print.sh
- scripts/clone-all-repos.sh
Refactors the `scripts/clone-all-repos.sh` script so that it passes `shellcheck`, includes some more informative log output, and flows in a bit simpler structure.
> Refactors clone-all-repos script

- .github/workflows/test-pull-request.yml
- builder/.github/workflows/create-release.yml
- builder/.github/workflows/test-pull-request.yml
- implementation/.github/workflows/create-draft-release.yml
- implementation/.github/workflows/test-pull-request.yml
- language-family/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/test-pull-request.yml
All workflows should use Go v1.17 or higher.
> Bumps Go to 1.17 across all workflows

- builder/scripts/.util/tools.sh
- builder/scripts/smoke.sh
> Adds installation util and corrects var name

- actions/release/notes/Dockerfile
- actions/release/notes/entrypoint
> actions/release/notes: Do not hardcode, use latest jam

- implementation/.github/workflows/push-buildpackage.yml
- language-family/.github/workflows/push-buildpackage.yml
As decided in [RFC 39](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0039-semantic-version-tags.md)
> Also push MAJOR and MAJOR.MINOR tags when releasing

- actions/release/notes/action.yml
- actions/release/notes/entrypoint
> actions/release/notes: Configurable buildpackage path

- .github/workflows/update-tools.yml
- builder/scripts/.util/tools.json
- builder/scripts/smoke.sh
- language-family/scripts/.util/tools.json
> Removes unnecessary tools from builder and language family repos

- builder/.github/labels.yml
- implementation/.github/labels.yml
- language-family/.github/labels.yml
> Adds good first issue label

- actions/tag/calculate-semver/action.yml
- actions/tag/calculate-semver/entrypoint/main.go
- actions/tag/calculate-semver/entrypoint/main_test.go
- implementation/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/create-draft-release.yml
> Adds a ref-name parameter to the calculate semver action

- actions/tag/calculate-semver/action.yml
Makes ref-name a required field
> Update Calculate Semver action.yml

- actions/builder/update/action.yml
> Uses latest jam version instead of one from .util/tools.json

- actions/builder/update/action.yml
Use the proper interpolation format
> Update the GITHUB_TOKEN

- actions/builder/update/action.yml
- builder/.github/workflows/update-builder-toml.yml
> Update builder action

- actions/builder/update/action.yml
> Removes erroneous env setting

- implementation/.github/workflows/lint.yml
- language-family/.github/workflows/lint.yml
> Adds now required setup-go step to link workflow

- implementation/.github/workflows/update-dependencies.yml
- language-family/.github/workflows/update-buildpack-toml.yml
> Makes update crons hourly instead of every 15 minutes

- implementation/.github/workflows/check-pr-labels.yml
- implementation/.github/workflows/label-pr.yml
- language-family/.github/workflows/check-pr-labels.yml
- language-family/.github/workflows/label-pr.yml
Recent changes to the autolabeler workflow were so effective at reducing friction in the autolabeling process that they created an infinite label/unlabel loop! Whoops! (e.g. https://github.com/paketo-buildpacks/go-mod-vendor/pull/318)
Rolling back these changes before the github config cron job runs tonight.
> Revert labeler changes

- scripts/repo_rules.sh
Signed-off-by: Forest Eckhardt <feckhardt@pivotal.io>
#442 Removes a status check that used to be required on all buildpack repos. It introduces a new status check (Label PR) that needs to be required on all buildpack repos.
> Update name of required PR label check

- implementation/.github/workflows/label-pr.yml
- language-family/.github/workflows/label-pr.yml
- scripts/repo_rules.sh
To save maintainers the toil of having to change which status check is Required as part of repos' branch protection rules, renames the Semver check to match the old name
> Rename autolabeler status check

- .github/workflows/test-pull-request.yml
- builder/.github/workflows/create-release.yml
- builder/.github/workflows/test-pull-request.yml
- implementation/.github/workflows/create-draft-release.yml
- implementation/.github/workflows/lint.yml
- implementation/.github/workflows/test-pull-request.yml
- language-family/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/lint.yml
- language-family/.github/workflows/test-pull-request.yml
> Upgrade to go1.18 in workflows

- actions/pull-request/checkout-branch/entrypoint
May help to resolve [issues](https://github.com/paketo-buildpacks/dotnet-core-sdk/runs/5997876562?check_suite_focus=true) where actions are failing to checkout a branch.
> Mark $GITHUB_WORKSPACE as safe for git

- actions/pull-request/approve/entrypoint
Resolve[ failures](https://github.com/paketo-buildpacks/stack-usns/runs/6010562120?check_suite_focus=true) in the approve PR action the same way we did in #454
> Mark GITHUB_WORKSPACE as safe for git in approval action

- actions/pull-request/auto-semver-label/action.yml
- actions/pull-request/create-commit/entrypoint
- actions/pull-request/merge/entrypoint
- actions/pull-request/open/entrypoint
- actions/pull-request/push-branch/entrypoint
- actions/pull-request/rebase/entrypoint
- actions/release/notes/entrypoint
Addresses automation failures like: https://github.com/paketo-buildpacks/full-builder/runs/6011835387?check_suite_focus=true
> Mark workspace as safe in all actions

- actions/release/notes/entrypoint
> roll back safe GITHUB_WORKSPACE for release note action

- actions/dispatch/entrypoint/main_test.go
- actions/release/create/entrypoint/main_test.go
- scripts/time-to-merge/internal/pull_request.go
- scripts/time-to-merge/internal/repository.go
Remove deprecated ioutil package.
> Remove deprecated ioutil package.

- actions/stack/release-notes/action.yml
- actions/stack/release-notes/entrypoint/main.go
- actions/stack/release-notes/entrypoint/template.md
- stack/.github/workflows/create-release.yml
#484 
If a user provides the `force` input to a workflow and a package is removed, a release is allowed to occur.
> Allow the forcible removal of stack packages in the release workflow

- stack/.github/workflows/push-image.yml
Fixes a small typo in the `push-image` workflow for stacks.
> Fix push-image workflow typo

- language-family/scripts/integration.sh
Fixes broken test runs like: https://github.com/paketo-buildpacks/go/runs/7322479197?check_suite_focus=true
> Correct typo in language family integration test script

- implementation/.github/.patch_files
- language-family/.github/.patch_files
So that PRs [like this](https://github.com/paketo-buildpacks/dotnet-publish/pull/343) can auto-merge in the future.
> Add go module updater to patch allowlist

- implementation/.github/workflows/go-get-update.yml
I'm seeing some issues running this workflow in practice, looks like the branch needs to be created first.
https://github.com/paketo-buildpacks/cpython/actions/workflows/go-get-update.yml
> Need to checkout branch automation/tools/go-get-update

- stack/.github/workflows/push-image.yml
See https://github.com/paketo-buildpacks/bionic-base-stack/runs/7677819194?check_suite_focus=true
and https://github.com/paketo-buildpacks/github-config/pull/517#discussion_r933391917. Returning this to the previous command.
> stacks: Fix command syntax for configuring docker

- library/.github/.patch_files
> [Library] update patch files

- stack/scripts/create.sh
This PR adds support for the `--secret` flag to the stack creations script. This feature is already supported by `jam create-stack`, so we are just exposing it to the helper script.
Stacks that wish to use the shared config but that require secrets need this flag exposing.
> Add secrets support to stack creation script.

- implementation/.github/workflows/update-dependencies-from-metadata.yml
Fixes shellcheck errors in the new dependency update workflow per @fg-j's request.
> fix dependency workflow shellcheck errors

- actions/release/notes/entrypoint
Resolves @robdimsdale comment on https://github.com/paketo-buildpacks/github-config/pull/569#issuecomment-1259996173
> release note action: re-add --show-error flag to curl

- library/.github/workflows/approve-bot-pr.yml
- library/.github/workflows/codeql-analysis.yml
- library/.github/workflows/create-draft-release.yml
- library/.github/workflows/label-pr.yml
- library/.github/workflows/lint-yaml.yml
- library/.github/workflows/lint.yml
- library/.github/workflows/test-pull-request.yml
- library/.github/workflows/update-github-config.yml
[Library] Use dynamic base branch for update-github-config PRs
> [Library] Use dynamic base branch for update-github-config PRs

- implementation/.github/.patch_files
- language-family/.github/.patch_files
Update Patch Files [Implementation, Language Family]
> Update Patch Files [Implementation, Language Family]

- implementation/.github/workflows/update-dependencies-from-metadata.yml
See https://github.com/paketo-buildpacks/poetry/pull/117 and https://paketobuildpacks.slack.com/archives/CUD6UTCJW/p1665065980980549 for context
> Always run the 'Update buildpack.toml' step

- implementation/.github/.patch_files
Add New Dep Workflow to Patch Files
> Add New Dep Workflow to Patch Files

- actions/issue/add-to-project/Dockerfile
- actions/issue/add-to-project/action.yml
- actions/issue/add-to-project/entrypoint
This action adds the given issue to a github project board and (optionally) sets a custom field of type Single-Select to the given value.
(e.g. in the Paketo Workstreams board, adding an issue and setting its "Workstream" field) This action is designed to be chained with `actions/issue/file`.
Here's a typical example of usage:
```yaml
- name: File Issue
id: file-issue
uses: paketo-buildpacks/github-config/actions/issue/file@main
with:
token: <token>
repo: ${{ github.repository }}
issue_title: "Some title"
issue_body: |
Some issue body
- name: Add issue to project
id: issue-to-proj
uses: paketo-buildpacks/github-config/actions/issue/add-to-project@action-issue-add-to-proj
with:
token: <token>
issue-node-id: ${{ steps.file-issue.outputs.node-id }}
project-org: my-org
project-num: 24 …
```
> add action that adds an issue to project and set fields

- .github/.yamllint
- stack/.github/workflows/create-release.yml
This PR updates the yamllint rules to encode some of the patterns we already adhere to.
This PR also makes some minor, non-functional, changes to workflows.
Make yamllint more useful to us; catching more things we care about.
> Update yamllint config

- .github/workflows/approve-bot-pr.yml
> Add workflow to approve bot PRs to this repo.

- language-family/.github/workflows/create-release-issue.yml
> Add weekly release issue automation

- .github/workflows/test-pull-request.yml
- builder/.github/workflows/create-release.yml
- builder/.github/workflows/test-builder.yml
- builder/.github/workflows/test-pull-request.yml
- implementation/.github/workflows/create-draft-release.yml
- implementation/.github/workflows/go-get-update.yml
- implementation/.github/workflows/lint.yml
- implementation/.github/workflows/test-pull-request.yml
- implementation/.github/workflows/update-dependencies-from-metadata.yml
- language-family/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/lint.yml
- language-family/.github/workflows/test-pull-request.yml
- library/.github/workflows/create-draft-release.yml
- library/.github/workflows/lint.yml
- library/.github/workflows/test-pull-request.yml
- stack/.github/workflows/create-release.yml
- stack/.github/workflows/test-pull-request.yml
Go 1.19 has been out for a while now. Let's use it.
> Run all workflows with Go 1.19

- .github/workflows/test-pull-request.yml
Upload the PR event payload to enable subsequent actions (e.g. auto-approving) to work.
Resolves #689
> Upload PR event-payload for PRs to this repo.

- actions/stack/release-notes/action.yml
- actions/stack/release-notes/entrypoint/main.go
- actions/stack/release-notes/entrypoint/template.md
> Stack release notes act: Support CVE scan report of stack imgs

- .github/workflows/test-pull-request.yml
- builder/.github/workflows/create-release.yml
- builder/.github/workflows/test-builder.yml
- builder/.github/workflows/test-pull-request.yml
- implementation/.github/workflows/create-draft-release.yml
- implementation/.github/workflows/go-get-update.yml
- implementation/.github/workflows/lint.yml
- implementation/.github/workflows/test-pull-request.yml
- implementation/.github/workflows/update-dependencies-from-metadata.yml
- language-family/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/lint.yml
- language-family/.github/workflows/test-pull-request.yml
- library/.github/workflows/create-draft-release.yml
- library/.github/workflows/lint.yml
- library/.github/workflows/test-pull-request.yml
- stack/.github/workflows/create-release.yml
- stack/.github/workflows/test-pull-request.yml
Let's use Go 1.20 to test/lint/build stuff in our workflows.
> Updates workflows to use Go 1.20

- .github/workflows/build-push-actions.yml
- actions/release/download-asset/README.md
- actions/release/find-asset/README.md
- actions/stack/get-usns/README.md
This PR fixes issues with #781 and expands it to include all the images we currently build and push.
Adding other triggers like push/cron is left as future work.
This workflow can be run manually to rebuild all images. See #781 for more context.
> Workflow to build and push action images

- stack/.github/workflows/test-pull-request.yml
This PR fixes the stack PR test workflow. It addresses items missed in #802.
PR tests are currently broken. This PR fixes them.
> Fix stack test PR workflow.

- implementation/.github/workflows/create-draft-release.yml
- implementation/.github/workflows/test-pull-request.yml
- language-family/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/test-pull-request.yml
- library/.github/workflows/create-draft-release.yml
- Removes tag checkout step in places where it is replaced by the action or appeared to not need the tags
> Adds fetch-tags to checkout action

- .github/workflows/test-pull-request.yml
- builder/.github/workflows/create-release.yml
- builder/.github/workflows/test-builder.yml
- builder/.github/workflows/test-pull-request.yml
- implementation/.github/workflows/create-draft-release.yml
- implementation/.github/workflows/lint.yml
- implementation/.github/workflows/test-pull-request.yml
- implementation/.github/workflows/update-dependencies-from-metadata.yml
- language-family/.github/workflows/create-draft-release.yml
- language-family/.github/workflows/lint.yml
- language-family/.github/workflows/test-pull-request.yml
- library/.github/workflows/create-draft-release.yml
- library/.github/workflows/lint.yml
- library/.github/workflows/test-pull-request.yml
- stack/.github/workflows/create-release.yml
- stack/.github/workflows/test-pull-request.yml
> Configure go-version to always be stable version

- actions/buildpack/update/action.yml
Supports changes introduced in https://github.com/paketo-buildpacks/jam/pull/313
> Update buildpack action: add support for `--patch-only`

- actions/pull-request/open/entrypoint
> open PR action: fix typo

- actions/release/publish-drafts/Dockerfile
- actions/release/publish-drafts/action.yml
- actions/release/publish-drafts/entrypoint
- implementation/.github/workflows/publish-releases.yml
Part of https://github.com/paketo-buildpacks/github-config/issues/925
- Adds a workflow to the implementation buildpacks, to release latest drafts every Wednesday morning.
- Adds an action that can be used to release just the latest draft, or all draft releases
I have gone with the cron job implementation here, instead of running this workflow everytime there is a draft release for a few reasons:
- Maintainers can expect a uniform release schedule. This helps with mental overhead and ensures if there are last-minute changes to include in a release, we know exactly when the release will go out and can plan accordingly
- Changes can be grouped together in releases, rather than creating many releases for every individual change, which might be noisy
There may be some benefits from going with …
> add workflow/action to auto-release buildpacks

- actions/release/publish-drafts/entrypoint
we should publish in ascending order, rather than descending, so that the highest semver is published last
> publish-drafts action: fix bug

- .github/workflows/update-tools.yml
Fixes failures in the update tools workflow like https://github.com/paketo-buildpacks/github-config/actions/runs/10238813133/job/28323655306
> Fix tool update workflow

- .github/renovate.json
Fix for the renovate configuration which is referenced in the repo.
> Fix referenced renovate config

- .github/renovate-config.js
- .github/renovate.json
- renovate/renovate-default.json
- renovate/renovate-metabuildpack.json
- renovate/renovate-tooling.json
> Fix renovate config

- .github/renovate.json
- renovate/renovate-tooling.json
> Adjust renovate config

- renovate/renovate-default.json
> Disable dependency dashboard

- .github/renovate-config.js
- README.md
This PR:
* adds libnodejs to renovate
* adds cpython to renovate
* Fixes a link pointing to the correct file
> Adding libnodejs and cpython to renovate

- language-family/scripts/package.sh
> Remove debugging output from language family package.sh script
