paketo-buildpacks/github-config

actions/dispatch/entrypoint/main.go, actions/dispatch/entrypoint/main_test.go
Co-authored-by: Arjun Sreedharan <asreedharan@vmware.com>
This resolves a blocker mentioned in #6, and useful for implementation cnbs that are referenced in multiple language families.
cc @thitch97
=> actions/dispatch: support dispatch to multiple target repos

actions/tag/entrypoint, implementation/.github/workflows/create-release.yml
This change make it so that the version sting is v prepended for the github tag and release name but no where else. This was causing issues creating buildpackages because the versions that we provided in buildpack.tomls of the implementation buildpacks and meta buildpacks did not line up.
I decided to keep the v prepended to the tag and title on github on after reading [this](https://semver.org/#is-v123-a-semantic-version) from the semver spec.
=> Changes versioning logic

.github/data/implementation-cnbs, .github/data/language-family-cnbs, .github/workflows/notify-implementation.yml, README.md, implementation/.github/workflows/receive-github-config-updates.yml, implementation/.mergify/config.yml, scripts/bootstrap.sh, scripts/sanity.sh
- list of target repos in .github/data
- worklow in .github notifies target repos on relevant change
- implementation/.github has workflow to receive notification
and create PR
- mergify config will auto merge the PR at the target
See [README.md](https://github.com/paketo-buildpacks/github-config/blob/propagate-implementation/README.md) for expected use
=> Propagate changes to implementation-cnbs

implementation/.github/workflows/receive-github-config-updates.yml
- renames DEPLOY_KEY_PRIVATE to PAKETO_BOT_SSH_KEY
- corrects action github repo name
=> Resolves integration issues with sync script

actions/release/create/action.yml, actions/release/create/entrypoint/main.go, actions/release/create/entrypoint/main_test.go
The body field used to be required, but we have cases where we don't
want to specify a body for the release.
=> Allows the "body" field to be omitted when creating a release

actions/tag/entrypoint
Just a small quality of life improvement.
Before these changes:
re-running workflows to create a file would tag a commit a second time and create an awkward unusable duplicate draft release.
After these changes:
re-running workflows that have cut a release will error out when trying to bump to a new tag.
Here is an example of this working: 
https://github.com/dwillist/puma/runs/721553534
=> add check for already commited tags

language-family/.github/workflows/push-buildpackage.yml
We've replace using docker to push these images because the `docker
image import` command loses metadata for the image that is then missing
on the remote. Skopeo keeps this metadata and doesn't use the docker
daemon.
=> Uses skopeo to push buildpackages to GCR

implementation/scripts/build.sh
- because go does not let you import from main package
=> update build.sh to support putting main.go in run directory

implementation/scripts/.util/tools.sh, language-family/scripts/.util/tools.sh
- Imagine a case where the go.mod of the cnb does not list
libcfbuildpack. Then, you'll have to "get" it.
=> scripts/tools.sh: Do not assume package exists

implementation/scripts/build.sh
Now that all buildpacks are either using `cmd/{detect,build}/main.go` or `run/main.go`, this extra codepath is no longer needed.
=> Removes unused codepath in implementation/scripts/build.sh

actions/release/reset-draft/action.yml, actions/release/reset-draft/entrypoint/main.go, actions/release/reset-draft/entrypoint/main_test.go, actions/tag/action.yml, actions/tag/entrypoint
These changes to the `release/reset-draft` and `tag` actions will allow administrators to control more directly what version number will be used when cutting a new draft release. To change the release major or minor version, administrators will be able to draft a new empty release with that version bump and then re-trigger the "Create Draft Release" workflow on their repository.
=> Draft releases can be forced to specify a version

implementation/.mergify/config.yml, language-family/.mergify/config.yml
This adds an upstream configuration file now that we have decided on a preliminary workflow for auto-merging dependabot updates with Mergify.
**Things to note:**
- The Mergify bot will need to be added to the list of users allowed to push to the base branch on each repo. To do this, navigate to the 'Branches' tab in the repo settings and select **"Restrict who can push to matching branches"**. Add `mergify` and the relevant list of maintainers for that repo to the allowed list.
- The `strict rebase` solution we have opted for has potential [drawbacks](https://doc.mergify.io/actions.html#strict-rebase) that may arise during our testing.
- The `bot_account` field specifies the account that will be used by Mergify when rebasing branches as it will need authorization.
=> Updates upstream Mergify config

actions/sync/entrypoint, language-family/.github/workflows/update-buildpack-toml.yml
git-branch verbose also prints out the commit subject line for each
HEAD. So a grep matches if the subject has something like "Merge pr from
@branch".
See:
- https://github.com/paketo-buildpacks/php-dist/actions/runs/190512860
-
https://github.com/paketo-buildpacks/php-composer/actions/runs/190512856
it looks like the check matches on:
> git branch -vv -a | grep "automation/github-config/update"
master  2985d66 [origin/master] Merge pull request #76 from paketo-buildpacks/automation/gi
thub-config/update
...
=> Fix git branch exist check command

README.md, scripts/repo_rules.sh
This script can be used to document recommended repo settings
for paketo cnbs.
Script validates settings of the given repo.
Only branch protection rules are validated in this commit.
More rules can be added later.
=> scripts: script to validate repo settings

actions/sync/entrypoint
- if there are no changes to current_repo, don't try to make a commit
- tested this action on a personal repo, and saw the sync workflow pass when no change was made
=> Modify sync action to check if there are any changes to commit

implementation/.github/workflows/send-dependency-update.yml
This change makes managing language family membership of each
implementation cnb more easy and transparent.
To make use of this, you'd do the following in your
implementation cnb:
- remove the secret `LANGUAGE_FAMILY_REPO`
- create a file `.github/language-family-membership` whose contents must
be each target language family per line (syntax: `<org>/<repo>`)
- you may add the this file to `.github/.syncignore`
=> impl->fam dispatch: read lang fam list from file not secret

implementation/scripts/.util/print.sh, implementation/scripts/.util/tools.sh, implementation/scripts/integration.sh, implementation/scripts/unit.sh, language-family/scripts/.util/print.sh, language-family/scripts/.util/tools.sh, language-family/scripts/integration.sh
These tests are used to validate pull requests and it's
very easy to overlook focused tests and assume the change
in PR satisfies the entire test suite.
=> Make unit/int tests exit non-zero when tests are focused

actions/pull-request/open/entrypoint
If the token in invalid, github api responds with the following:
```
{
"message": "Bad credentials",
"documentation_url": "https://docs.github.com/rest"
}
```
The length of above is "2" and could be misinterpreted as
2 existing pull requests. Therefore, check for error message
before counting the length.
E.g. of bug in action:
https://github.com/sophiewigmore/full-builder/actions/runs/284409623
=> actions/pr/open: validate response before counting

implementation/scripts/build.sh
Seems to help with resolving upx-compressed binaries that experience segmentation faults on invocation.
=> Build position-independent executables

language-family/.github/workflows/update-buildpack-toml.yml
Removes the `push` event trigger than was left in the workflow for testing purposes. This workflow should only trigger on a schedule.
Please confirm the following:
=> Don't trigger update buildpack.toml workflow on push

implementation/.github/workflows/update-github-config.yml, language-family/.github/workflows/update-buildpack-toml.yml, language-family/.github/workflows/update-github-config.yml
Including `workflow_dispatch` as an event trigger on these scheduled workflows will allow us to trigger them manually on demand. On the `Actions` page, the manual trigger looks like this:
=> Allows schedules workflows to be manually triggered

implementation/scripts/integration.sh
Newer occam/freezer uses the jam cli directly
See https://github.com/ForestEckhardt/freezer/compare/v0.0.3...v0.0.5
=> impl/scripts: install jam whether packit compliant or not

implementation/.github/workflows/auto-merge.yml, language-family/.github/workflows/auto-merge.yml
As outlined in an [issue on octokit](https://github.com/octokit/octokit.net/issues/1763), the `unstable` state is defined as "Failing/pending commit status that is not part of the required status checks. Merging is allowed."
Running the "Auto Merge" workflow itself induces an `unstable` state as it is a pending check that is not part of the required status checks. This is different than the `blocked` state which is induced by running one of the required status checks. Either way, a merge will only be possible if all of the required checks have passed and so it should be safe to allow the "Auto Merge" workflow to attempt to merge the PR given an `unstable` state.
=> Allows automerging PRs in the 'unstable' state

implementation/.github/workflows/create-draft-release.yml, implementation/.github/workflows/test-pull-request.yml
When running the integration tests in the implementation buildpacks workflows, use the `--use-token` flag to avoid rate limiting.
=> add the --use-token flag to implementation integration.sh

implementation/.github/workflows/push-buildpackage.yml, language-family/.github/workflows/push-buildpackage.yml
Switching to `skopeo login` seems like it may fix these push failures we've seen in our workflows: https://github.com/paketo-buildpacks/dotnet-core-runtime/runs/1817049406?check_suite_focus=true.
=> Use skopeo login instead of docker login when pushing

implementation/.github/workflows/push-buildpackage.yml, language-family/.github/workflows/push-buildpackage.yml
The original command, `docker login`, handled the case where we don't specify a registry to log in to. `skopeo` requires that we always set the registry.
=> Include the registry when logging in to dockerhub

actions/sync/action.yml, actions/sync/entrypoint, implementation/.github/workflows/update-github-config.yml, language-family/.github/workflows/update-github-config.yml
The sync action can be reduced to simply performing the `rsync` of the shared files between the `github-config` repo and the buildpack repo. We can reuse all of the existing `pull-request/*` actions to replace everything else that this workflow needs.
=> Refactors sync action to only perform rsync

actions/pull-request/create-commit/action.yml, actions/pull-request/create-commit/entrypoint
Accepts GPG signing key and keyid as optional arguments to the commit action so that paketo-bot commits can be "verified".
Workflows will need to be updated to provide GPG_SIGNING_KEY and key ID secrets to use the signing capability.
This will allow paketo-bot PRs to pass the verification check introduced in #219
=> optionally load GPG key for paketo bot before committing

builder/.github/workflows/update-builder-toml.yml
I added a manual trigger to the builder update workflow for the builder repos
Sometimes GHA doesn't strictly follow the cron schedule. It'd be nice to kick off a builder update manually if there's an update we want to get out quickly, rather than waiting around for a scheduled job.
=> add manual trigger to builder update workflow

builder/.github/workflows/update-github-config.yml
Fixes the typo that caused builders to update from the implementation directory.
=> Builders should update from the right location

builder/.github/workflows/update-builder-toml.yml, builder/.github/workflows/update-github-config.yml, implementation/.github/workflows/update-github-config.yml, language-family/.github/workflows/update-buildpack-toml.yml, language-family/.github/workflows/update-github-config.yml
Signed-off-by: Forest Eckhardt <feckhardt@pivotal.io>
Now, bot PRs opened by paketo-bot will be verified. These PRs will pass our check for unverified commits and should automerge (once again).
=> sign commits in workflows that make paketo bot commits

actions/pull-request/create-commit/Dockerfile, actions/pull-request/create-commit/entrypoint
also adds 'quiet' config to gpg key import
Fixes a bug where commits can't be signed because `gpg` isn't installed and incorrect flag used for `base64`. Also configures `gpg` to install the key quietly.
=> fixes create-commit action to install tool for signing

builder/.github/workflows/test-pull-request.yml
We now check for human and unsigned commits before auto-merging PRs to implementation and language family buildpack repos. We should do the same for builders' repos.
=> checks for human or unsigned commits before auto-approving builder PRs

README.md, scripts/bootstrap.sh
The `./scripts/bootstrap.sh` script should also support builder repos. This is helpful if we ever need to manually sync the repo GitHub config.
=> Allows builders to be bootstrapped

actions/pull-request/create-commit/action.yml, actions/pull-request/create-commit/entrypoint
The committer name and email can now be overridden in a workflow. The defaults will remain what their hardcoded values were originally, which should mean that we won't need to update any existing workflow references.
This allows other to reuse this action with their own bot.
=> Parameterizes committer name and email in create-commit action

actions/pull-request/approve/Dockerfile, actions/pull-request/approve/action.yml, actions/pull-request/approve/entrypoint, actions/pull-request/merge/Dockerfile, actions/pull-request/merge/action.yml, actions/pull-request/merge/entrypoint, actions/pull-request/open/Dockerfile, actions/pull-request/open/entrypoint, actions/pull-request/rebase/Dockerfile, actions/pull-request/rebase/action.yml, actions/pull-request/rebase/entrypoint, builder/.github/workflows/auto-merge.yml, builder/.github/workflows/test-pull-request.yml, implementation/.github/workflows/auto-merge.yml, implementation/.github/workflows/test-pull-request.yml, language-family/.github/workflows/auto-merge.yml, language-family/.github/workflows/test-pull-request.yml
- removes extra checks in approve action that are unneeded
- simplifies action APIs for actions using newer gh
We have been using a rather old version of the `gh` CLI. This updates the actions that use `gh` to `v1.7.0`. Updating allows us to streamline the API for some of these actions to drop certain fields like `user` because the authentication can be performed with only a token.
Additionally, this includes the removal of a check in the `pull-request/approve` action that asserts bot PRs were opened by either `paketo-bot` or `dependabot[bot]`. This check is unnecessary because that is already checked earlier in the workflows that use this action. It also makes it easier to use this action outside of Paketo buildpacks.
=> Updates gh in actions to 1.7.0

builder/.github/workflows/create-release.yml
Since [this change](https://github.com/paketo-buildpacks/github-config/commit/3e0e4cdd89ef38e20dd9a7165645d1d2c6add955) to the builders repo removed the `.github/pack-version` file and replaced it with `tools.json`, the Create Release workflow has been failing on the builders repos. (e.g. [this run](https://github.com/paketo-buildpacks/full-builder/runs/2228819401?check_suite_focus=true)) The change reads the pack version from the correct file location and outputs the version in the right form (`0.18.0`, not `v0.18.0`) to be accepted by the pack installation Github Action.
=> fix pack installation in create release workflow to use tools.json

builder/.github/workflows/update-builder-toml.yml
so that builder-update action doesn't re-add broken lifecycle
=> (temporarily) remove cron job from builder updates

builder/.github/workflows/update-builder-toml.yml
Previously, cron job to update builder was turned off because lifecycle version 0.11.0 had a significant bug that broke builds on GCP vms. Now that they've released lifecycle 0.11.1, which patches this bug, we're okay to allow the builders to pull the latest lifecycle image once again.
=> turn on update builder cron job

builder/.github/labels.yml, builder/.github/workflows/synchronize-labels.yml, implementation/.github/labels.yml, implementation/.github/workflows/synchronize-labels.yml, language-family/.github/labels.yml, language-family/.github/workflows/synchronize-labels.yml
Adds workflows that will look at `labels.yml` file and update the labels on a repository. This will keep the labels we have on repos more uniform. This uses the same workflow as the [Java buildpacks](https://github.com/paketo-buildpacks/java/blob/main/.github/workflows/synchronize-labels.yml).
=> Add GHA for synchronizing repository labels

actions/release/notes/action.yml
I broke the action in #260 by including an extra `runs` block. I thought it was previously missing. This removes the extra block so that the action can run successfully.
=> Removes extra runs block from release notes action

builder/.github/workflows/test-pull-request.yml, implementation/.github/workflows/test-pull-request.yml, language-family/.github/workflows/test-pull-request.yml
Recently, we have been seeing PRs that are opened by Dependabot failing due to a token permissions issue when the Test PR workflows attempt to auto-approve the PR. Our understanding is that this behavior by GitHub is correct, but it breaks our current workflow for these types of PRs. We would like to move to a workflow that will work in all cases.
This PR is the start of an attempt to create a pair of workflows that work in conjunction to give us this outcome. First, the existing portions of the Test PR workflow will execute, then a subsequent workflow that is separate, and with elevated permissions will run to perform the step to auto-approve the bot PR. In order to pass details about the Test PR to the second workflow, we will need to upload that information to the workflow's artifact …
=> Uploads workflow event payload after tests for PRs

actions/tag/increment-tag/entrypoint
When a repo has tags on it that don't look like `v1.2.3`, the increment-tag action would pick up on one of those other tags (if the most recent) and increment it. An example of this can be seen in [this failure on the dotnet core repo](https://github.com/paketo-buildpacks/dotnet-core/runs/2400967916?check_suite_focus=true), where we now automatically  tag `docs/v1.2.3` for each released `v1.2.3`. This change updates the action to only look for and increment standard version tags.
=> don't increment tags that aren't semver versions

.github/workflows/test-pull-request.yml, builder/.github/workflows/create-release.yml, builder/.github/workflows/test-pull-request.yml, implementation/.github/workflows/create-draft-release.yml, implementation/.github/workflows/test-pull-request.yml, language-family/.github/workflows/create-draft-release.yml, language-family/.github/workflows/test-pull-request.yml
go 1.16 has a few bugs like https://golang.org/issue/44812
(cmd/go: 'go get' does not add missing hash to go.sum when ziphash file missing from cache)
that was fixed in 1.16.1.
Go.sum had to be recalculated for this which could possibly have a
connection with above bug:
https://github.com/paketo-buildpacks/php-composer/runs/2096238683?check_suite_focus=true#step:5:489
Also trying to make sure the following error is not due to a golang
issue since I can run it fine locally on go 1.16.3
https://github.com/paketo-buildpacks/php-web/runs/2410350544?check_suite_focus=true
=> Always use latest patch of go 1.16

actions/release/notes/entrypoint
The current implementation may produce a changelog that has duplicate entries for some PRs that contain more than 1 commit. This change ensures that we only have one entry per PR.
=> Remove duplicate entries in release changelog

.github/workflows/update-tools.yml, actions/tools/latest/Dockerfile, actions/tools/latest/action.yml, actions/tools/latest/entrypoint
We have a `tools.json` that holds references to the latest versions of `pack` and `jam` that we use for each of the `builder`, `implementation`, and `language-family` scripts. This PR includes a new action for fetching the latest release of a tool, and then also a workflow to update the versions of `jam` and `pack` when they are released.
Resolves #167
Resolves #190
=> Adds action and workflow to keep jam and pack updated

language-family/.github/workflows/tag-docs-release.yml
In order to roll Hugo modules out to the other language family repos besides dotnet-core, we need to pull [this workflow](https://github.com/paketo-buildpacks/dotnet-core/blob/6a1330795ef13f26bfd5bdbc6c99d053b3944e7c/.github/workflows/tag-docs-release.yml) that automatically creates `docs/v1.2.3` tags on each buildpack release so that versions of docs modules are cut at the same time as buildpack versions.
=> automatically push tags docs/v1.2.3 for each v1.2.3 release

implementation/scripts/integration.sh, implementation/scripts/package.sh
Now that the majority of the buildpacks are using `packit` as their library, we can remove a bunch of extraneous files by swapping the conditional in the packaging script that determines which tool to use to package the buildpack. Once this is merged and propagates to all of the implementation repos, we can remove all of the `.packit` files from those repos. We can also remove the `.packit` file from the `bootstrapper`.
=> Swaps .packit file references for .libbuildpack

.github/dependabot.yml, builder/.github/dependabot.yml, implementation/.github/dependabot.yml, language-family/.github/dependabot.yml
The addition of `github-actions` to the dependabot configuration appears to be causing thrashing where dependabot bumps an action forward to a new version, and then the github-config update workflow bumps in back. This will continue in an endless loop.
This PR removes the dependabot configurations for `github-actions` in each repo type and will instead update them from this repo and propagate those updates via the github-config update workflow.
=> Update workflow actions through this repo

language-family/.github/workflows/tag-docs-release.yml
Currently, tag docs release workflows fail [like this](https://github.com/paketo-buildpacks/go/runs/2634100845?check_suite_focus=true) because the Push Branch action doesn't use the right syntax for pushing up a new tag. This PR corrects the workflow, as evidenced by [the workflow used in this passing run](https://github.com/paketo-buildpacks/dotnet-core/actions/runs/861826689/workflow)
=> correct tag pushing syntax

implementation/.github/workflows/push-buildpackage.yml, language-family/.github/workflows/push-buildpackage.yml
Maintainers may sometimes in error publish releases with
different versions on the release and in the buildpackage.
This validates the versions are same before pushing to
remote registries.
=> Push buildpackage: Check for version discrepancy

.github/.yamllint, .github/workflows/lint-yaml.yml, builder/.github/workflows/approve-bot-pr.yml, builder/.github/workflows/create-release.yml, builder/.github/workflows/lint-yaml.yml, builder/.github/workflows/synchronize-labels.yml, implementation/.github/workflows/approve-bot-pr.yml, implementation/.github/workflows/codeql-analysis.yml, implementation/.github/workflows/lint-yaml.yml, implementation/.github/workflows/lint.yml, implementation/.github/workflows/synchronize-labels.yml, language-family/.github/workflows/approve-bot-pr.yml, language-family/.github/workflows/lint-yaml.yml, language-family/.github/workflows/lint.yml, language-family/.github/workflows/synchronize-labels.yml
It really grinds my gears when I write or update a Github action and my hopes are dashed by YAML errors that I didn't catch.
This PR adds workflows that lint all the yaml files in a the `.github` directory using a common config that's checked into this repo at `.github/.yamllint`
Here's the linter: https://github.com/adrienverge/yamllint
and here's the docs about how configuration works: https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
I set up the config such that our existing workflows would require minimal changes to pass the linter. We can make these stricter as we see fit.
=> Lint workflows when they're changed in pull requests

builder/.github/labels.yml, implementation/.github/labels.yml, language-family/.github/labels.yml
Per https://github.com/paketo-buildpacks/rfcs/blob/main/text/0029-semantic-versioning.md#process,
these labels can be used to indicate that the change within a Pull
Request requires a major/minor/patch version bump in the next release.
=> Add semver labels for pull requests

builder/scripts/smoke.sh
The buildpackless builders use `jam` in their smoke tests to build a buildpack to run an app against. Therefore `jam` installation needs to be added to the smoke test script so that it will work for all builders.
=> Adds `jam` to builder smoke tests for buildpackless builders

implementation/scripts/integration.sh, language-family/scripts/integration.sh
paketobuildpacks/builder:buildpackless-base is live! Let's use it to speed up tests.
=> Make buildpackless base builder default for tests

actions/pull-request/auto-semver-label/check-files-changed.sh
Resolves #365 
When dependabot opens PRs, these are technically from "forks". Workflows run against these PRs don't have access to repo secrets. It'd be nice if the auto-label action doesn't fail with a big red X just because auth wasn't provided.
The action already "fails green" when the no label can be determined.
=> PR autolabeling should "fail green" when no auth is provided

actions/pull-request/auto-semver-label/check-files-changed.sh
I uncovered some edge cases where the autolabeler "fails green" when it probably shouldn't:
- when the allowlist file doesn't exist
- when the attempt to fetch the PR changed files fails
I added explicit failure cases for these.
=> Check autolabeler failure modes

actions/buildpack/update/action.yml
This pull request makes the path to the buildpack.toml/package.toml configurable.
A buildpack's descriptor must be named `buildpack.toml` but the source code repo may maintain
this descriptor file under different names. An example is when when the same repository is used to
generate different flavor of a buildpack with the same funtion. Such a buildpack source code repo may have
`buildpack-x.toml` and `buildpack-y.toml` to generated `id-x` and `id-y` buildpack respectively.
Tested out https://github.com/arjun024/python/blob/automation/buildpack.toml/update/.github/workflows/update-buildpack-toml.yml#L22-L26 with and without defaults.
See 
https://github.com/arjun024/python/commit/c9e97c4b0354e6d33c0f40581a6ebd30934335ab
and
https://github.com/arjun024/python/commit/4306f1d06283e100298bd0cc …
=> Actions/buildpack/update: make configurable

builder/.github/workflows/update-builder-toml.yml, builder/.github/workflows/update-github-config.yml, implementation/.github/workflows/update-github-config.yml, language-family/.github/workflows/update-github-config.yml
at different minutes past the hour for each type of repo; also run
builder updates hourly
The paketo-buildpacks org seems to be frequently bumping against the concurrency limits for GHA workloads. This PR decreases the frequency of github config updates to hourly. Implementations, language families, and builders will receive updates at staggered times during each hour. 
Also decreases the frequency of builder updates to hourly.
=> Decrease cron job frequency

actions/pull-request/auto-semver-label/action.yml
This action would prematurely remove the semver label from a PR before it figured out if it was able to add one automatically. This change just swaps these steps to do the check before removing and ultimately replacing the label. This should save us from having to reapply a label that gets accidentally removed by this action when it cannot apply the label itself.
=> Check that label can be applied before removing it

actions/pull-request/auto-semver-label/action.yml
So the autolabeler won't clear human-added labels if the PR can't be auto-labeled.
=> Only clear labels if autolabeler returns a result

builder/.github/workflows/update-github-config.yml, implementation/.github/workflows/update-github-config.yml, language-family/.github/workflows/update-github-config.yml
Hordes of github-config notifications can swamp maintainer inboxes and sometimes require maintainer intervention. I think it's sufficient for repos to automatically receive these updates once daily. If updates are needed sooner, the manual workflow trigger can be used. This hopefully reduces the overall number of PRs we have to deal with day to day.
The times are staggered to prevent overloading our worker pool.
=> Sync github config once daily

actions/pull-request/auto-semver-label/action.yml, actions/pull-request/auto-semver-label/check-files-changed.sh
When dependabot PRs go out to our repos, they require a lot of maintainer intervention since they aren't auto-labeled. 
The simplest mitigation I can think of is to automatically label dependabot PRs as patch changes. My reasoning is that dependency bumps that *shouldn't* be labeled as patch changes to the buildpack will cause test failures. The main dependency bump that I slightly worry about autolabeling as patch is packit. But:
- we usually mark unused structs, fields, functions as deprecated, which will cause linter failures
- otherwise, we add typically features that buildpack authors need to take action to use; simply bumping packit doesn't generally add buildpack features.
So I might be convinced that it's fine to label all dependency bumps as patches. Let's hash this question out …
=> Autolabel dependabot PRs as patch changes

implementation/.github/workflows/label-pr.yml, language-family/.github/workflows/label-pr.yml
The attempt to consolidate the PR label actions in #438 didn't quite work as intended, as evidenced [here](https://github.com/paketo-buildpacks/go-dist/actions/runs/1993426547). From the docs of the [github action that checks for labels](https://github.com/mheap/github-action-required-labels):
> By default this actions reads `event.json`, which will not detect when a label is added in an earlier step. To force an API call, set the `GITHUB_TOKEN` environment variable
=> Force label check to hit Github API

builder/.github/release-drafter-config.yml, builder/.github/workflows/create-release.yml
Currently, the Paketo Full Builder uses different release automation from the other builders. This is confusing to reason about. This PR sets up all the builders to use the same release automation that's [in the Full Builder repo](https://github.com/paketo-buildpacks/full-builder/blob/main/.github/workflows/create-release.yml). I use the release-drafter action instead of Paketo's bespoke semver versioning because the release-drafter supports assigning a "default" version to a release if PRs don't have labels. It's worked like a charm on the Full Builder repo for a while now.
=> Use same release automation for all builders

implementation/.github/workflows/label-pr.yml, language-family/.github/workflows/label-pr.yml
Should fix recurring issues we've seen with the Semver Labeling workflow in which the auto-labeling step fails because it cannot access the repository secrets. Screenshot of the issue of empty `GITHUB_TOKEN` is attached:
This PR uses the `pull_request_target` trigger instead of `pull_request` which gives the workflow access to repository secrets. 
**Important note** 
The "[Keeping your GitHub Actions and workflows secure: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)" blog post mentions that `you should make sure that you do not check out, build, or run untrusted code from the pull request with this event`. 
The [auto-label semver action](https://github.com/paketo-buildpacks/github-config/blob/main/actions/pull-request/auto-semver- …
=> Use pull_request_target trigger in auto-label workflow

actions/buildpack/update/action.yml
Allows users of this action who *don't* publish component buildpacks on the CNB registry to keep using the action.
=> Allow Turning off CNB URI Updates in buildpack/update action

actions/tag/increment-tag/entrypoint
* Currently when the optional `current_version` is not provided, the git command errors with
```
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
```
* Also when this failure happens, action still exits 0 - so set opt to error on failure
=> increment-tag: mark as safe dir & make action exit 1 on err

implementation/.github/workflows/lint.yml, language-family/.github/workflows/lint.yml
As various other golangci-lint GHA users [have noticed](https://github.com/golangci/golangci-lint-action/issues/297), sometimes the action runs slower than would be expected on your local machine, resulting in timeouts. This increases the timeout from the default (1 minute) to reduce maintainers' toil rerunning the linter.
Some examples of linter runs that timed out:
- https://github.com/paketo-buildpacks/go-build/actions/runs/2375799354/attempts/1
- https://github.com/paketo-community/go-generate/actions/runs/2378009981/attempts/1
=> Increase golangci-lint timeout

language-family/.github/workflows/update-buildpack-toml.yml
- we observe a failure of type 429 (too many requests) roughly 10-20% of the time.
- it is possible that this change will have no effect if the issue is
instead that all the buildpack.toml updates run at the same time. If
this is the case then we would expect to see the same failure rate,
just on a slower cadence.
=> Update buildpack.toml every six hours instead of every hour.

implementation/.github/workflows/codeql-analysis.yml
`github/codeql-action/*@v1` is being deprecated, so let's proactively bump to `@v2`.
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
=> Bump to `github/codeql-action/*@v2`

actions/stack/get-usns/entrypoint/go.mod, actions/stack/get-usns/entrypoint/go.sum, actions/stack/get-usns/entrypoint/main.go
Since setting up release failure notification issues on the new Jammy Tiny stack, we have already seen many instances of failed builds that occur because of intermittent 504 errors when polling for USNs. ([example](https://github.com/paketo-buildpacks/jammy-tiny-stack/issues/20))
All of these notifications are red herrings, because the issue usually disappears when the job runs again. It's creating a lot of notifications.
This PR just allows for a retry in instances where polling fails do to a 504 error, so we can hopefully get less failures during this step.
=> Retry stack USN polling on 504 error

builder/.github/workflows/push-image.yml
In [Builders RFC 0008](https://github.com/paketo-buildpacks/rfcs/blob/main/text/builders/0008-jammy-builders.md) it was agreed that the new jammy builders should be pushed to DockerHub repos whose names match their Github repos. 
For instance, images created by the https://github.com/paketo-buildpacks/builder-jammy-buildpackless-base repo should be published to `paketobuildpacks/builder-jammy-buildpackless-base:latest`. This makes it a lot easier to define a centralized Push Image workflow for builders. This adds one here, which will apply to the Jammy builders.
All 6 bionic builders currently use the `.syncignore` file to define their own Push Image workflows. This should continue until we can refactor those workflows and/or rename the existing builder repos to make the image pushing …
=> Add centralized builder Push Image workflow

implementation/.github/.patch_files, language-family/.github/.patch_files
The latest batch of `Update Github Config` PRs didn't auto-label because the newly added `builder.sh` util script was not in the patch files list for implementation/language family buildpacks!
=> add scripts/.util/builders.sh to patch files list

implementation/.github/workflows/create-draft-release.yml, implementation/.github/workflows/test-pull-request.yml, language-family/.github/workflows/create-draft-release.yml, language-family/.github/workflows/test-pull-request.yml
The change in #503 had an unintended side effect. PRs [stall](https://github.com/paketo-buildpacks/dotnet-core-sdk/pull/377) waiting for the `Integration Tests` job to run, since it's a required check. Github's branch protection rules match required checks by name. The new matrix strategy changed the name of integration test jobs. 
One solution would be to manually update the required checks for all ~100 paketo buildpack repos. This work would have to be repeated whenever we add a builder to our test matrix. 
This PR offers an alternative: a job that `needs` the matrix-ed integration tests and has the same old name, `Integration Tests`. This job is therefore already marked required on most repos. With this addition, existing branch protection rules will continue to work.
This PR also adds …
=> Gather PR integration test results in one job

stack/.github/workflows/create-release.yml, stack/.github/workflows/test-pull-request.yml, stack/scripts/create.sh
Signed-off-by: Sophie Wigmore <swigmore@vmware.com>
This PR adds support for the `--unbuffered` flag to the `jam create-stack` command for the `*-full-stack` repos (i.e `jammy-full-stack` and `bionic-full-stack`). This flag reduces memory usage for large stacks, meaning that we don't have to increase the swap size on resource constrained environments (e.g. github actions workers).
We have tested both code flows in the `jammy-full-stack` and `jammy-tiny-stack` and they both create the images succesfully.
=> Add --unbuffered option to stack creation script.

stack/.github/workflows/push-image.yml
Signed-off-by: Rob Dimsdale-Zucker <rdimsdale@vmware.com>
Bionic stacks should also get pushed to the unversioned legacy locations, as well as the versioned ones we were already pushing to.
=> Add unversioned legacy image locations to stack image pushing

actions/issue/file/action.yml
The auto-file automation creates a bunch of short-lived issues [like this one](https://github.com/paketo-buildpacks/dotnet-core-runtime/issues/361) because the search for existing issues doesn't account for closed issues. With this change, if `comment_if_exists` is true, the automation will look for open or closed issues with the desired tag. It will reopen the most recent tagged issue and then comment on it. 
🔍  Note: `gh issue reopen` exits 0 if the issue is already open, so there's no need to check the state of the issue.
=> Reopen existing auto-filed issues

implementation/.github/workflows/go-get-update.yml
I've been seeing some `Dependabot` alerts about transitive dependencies that usually seem fixed by running `go get -u`. Let's just keep those up-to-date automatically.
Example `Dependabot` alerts: https://github.com/paketo-buildpacks/cpython/security/dependabot?q=is%3Aclosed
Assumes that implementation and language family repos have a go.mod at the root
=> Add workflow to run 'go get -u' and create a PR.

stack/.github/workflows/push-image.yml
We should continue pushing the run image mirrors to GCR for Bionic only, since the builders reference this location.
This will  resolve issues like https://github.com/paketo-buildpacks/full-builder/issues/709 for future stack releases.
=> Stacks: Push Bionic run images to GCR

actions/issue/file/action.yml
In https://github.com/paketo-buildpacks/dep-server/issues/196, we saw an example of a workflow failure issue being reopened by GHA even though the dependencies of interest were different. This change makes it so that if an issue is reopened and/or commented on, the issue title must be what we expect it to be as well.
=> Fix issue-opening action

actions/release/create/entrypoint/go.mod, actions/release/create/entrypoint/go.sum, actions/release/create/entrypoint/main.go
This PR adds support for retrying file uploads during the release creation step. It uses exponential backoff, using https://github.com/paketo-buildpacks/github-config/pull/488 as an example.
The main motivation for this PR is the observation that the majority of workflow failures (outside of test failures) stem from errors that occur during upload of files during the release creation step. This seems to happen most often with the larger `tgz`/`cnb` files that comprise the buildpacks and stacks.
I have tested this logic locally by extracting this logic into a small `main.go` and I have observed that it retries on failure as expected. Additionally, I have validated that the upload can eventually succeed without issues (e.g. due to re-opening the file).
The commit looks like there are a lot …
=> Add exponential backoff failure handling to create-release file uploading

stack/.github/workflows/push-image.yml
Some stack Push actions are failing like [this](https://github.com/paketo-buildpacks/bionic-base-stack/actions/runs/2799074651) using the `gcloud auth` and `gcloud auth configure-docker gcr.io`.
This change simplifies both commands using the official Docker Login [Github Action](https://github.com/docker/login-action) to access the Paketo Buildpacks GCR Repository (these changes only applies to Bionic stacks)
Solves https://github.com/paketo-buildpacks/bionic-base-stack/issues/24, https://github.com/paketo-buildpacks/bionic-tiny-stack/issues/7, https://github.com/paketo-buildpacks/bionic-full-stack/issues/18
=> Change auth method to login into docker using gcr.io

stack/.github/workflows/push-image.yml
We see a failure when attempting to push images to gcr.io with skopeo. We probably need to explicitly log in with skopeo login similar to what we do to login to dockerhub.
We observed this change works by creating a [PR for the bionic tiny stack](
https://github.com/paketo-buildpacks/bionic-tiny-stack/pull/33) and seeing the workflows run succesfully.
=> Add explicit skopeo login to GCR when pushing image.

stack/.github/workflows/push-image.yml
We explicitly run `skopeo login` which does not rely on docker login.
We see [this change working on the bionic tiny stack](https://github.com/paketo-buildpacks/bionic-tiny-stack/actions/runs/2826213568).
=> Remove separate GCR login step from stack push image workflow.

actions/release/create/entrypoint/main.go, actions/release/create/entrypoint/main_test.go, actions/stack/get-usns/entrypoint/main.go
This PR changes the way we leverage exponential backoff to continue attempting the task until a duration is exceed (max time) rather than until a specific number of attempts have been made (max retries). This better aligns with what we care about - namely how long we have been trying to perform an action rather than how many times we have attempted it.
The change from 3 retries to 5 minutes also substantially increases how long we are willing to wait for a task to complete. In particular, we have observed that getting `503` while looking for USNs can take minutes, not seconds, to being working again. This will result in fewer failures getting USNs. Changing the create-release file upload is not necessary, but is done to reduce the cognitive overhead of having different limits on tasks …
=> Use max time rather than max attemps for exponential backoff.

implementation/.github/.patch_files, implementation/.github/workflows/go-get-update.yml
Manually labeling tons of `Running 'go get -u all'`PRs  is getting tedious. It would be nice if these PRs auto-labeled and thus auto-merged. 
Edit: I have also modified the workflow to run once per week, rather than once per day.
Maintainer question - could it be dangerous to always auto-label `go.mod` changes as patches? Any package bumps that are breaking should hopefully cause linting or test failures which is why I think this is fine.
=> add go.mod and go.sum to implementation patch list

actions/release/find-asset/entrypoint
The `browser_download_url` does not allow programatic access to assets from private repos. Instead we should use `url` which works equally well for release assets on public and private repositories.
=> Use url instead of brower_download_url when downloading release assets.

actions/sync/entrypoint
According to the `rsync` manpage, "Two -v options will give you information on what files are being skipped and slightly more information at the end."
When debugging why a `.syncignore` file is not working, it would be nice to see what `rsync` says it is doing.
=> Increase the verbosity of rsync in the sync action

actions/builder/update/action.yml, actions/buildpack/update/action.yml, actions/dependency/update/action.yml, actions/pull-request/approve/Dockerfile, actions/pull-request/check-human-commits/entrypoint, actions/pull-request/check-unverified-commits/entrypoint, actions/pull-request/merge/Dockerfile, actions/pull-request/open/Dockerfile, actions/pull-request/rebase/Dockerfile, actions/release/download-asset/entrypoint, actions/release/notes/entrypoint, actions/tools/latest/entrypoint, scripts/change_version.sh, scripts/clone-all-repos.sh, scripts/repo_rules.sh
This PR ensures that curl returns a non-zero exit code when there is a server error (e.g. 404). It also forces the printing of the error message to aid debugging of a failed curl invocation.
Currently, when an invocation of `curl` fails, if fails silently - proceeding on to the next part of the action/workflow. The failure therefore only shows up in an unrelated command that is trying to do something with the result of the curl (e.g. invoking a downloaded binary or reading a downloaded file).
It can be hard to recognize these failures as a `curl` failure, and, more importantly, we should fail the action/workflow at the point that `curl` fails, not later on.
=> Fail on curl errors

actions/builder/update/action.yml, actions/buildpack/update/action.yml, actions/dependency/update/action.yml, actions/pull-request/approve/Dockerfile, actions/pull-request/check-human-commits/entrypoint, actions/pull-request/check-unverified-commits/entrypoint, actions/pull-request/merge/Dockerfile, actions/pull-request/open/Dockerfile, actions/pull-request/rebase/Dockerfile, actions/release/download-asset/entrypoint, actions/release/notes/entrypoint, actions/tools/latest/entrypoint, scripts/change_version.sh, scripts/clone-all-repos.sh, scripts/repo_rules.sh
This reverts commit efcb7d64396ce104702b39cb912e44e4df743f49.
We notice that our workflows run on Ubuntu 20.04 which has a version of curl that is too old for the `--fail-with-body` flag. We revert the previous commit while we decide on the best path forward.
=> Revert "Fail on curl errors"

implementation/.github/workflows/test-pull-request.yml, language-family/.github/workflows/test-pull-request.yml
This PR fixes the logic for the dynamic matrix `roundup` job for the integration tests.
* Currently if one or more of the matrix jobs fails, the `roundup` job never runs and is considered `skipped`.
* You can validate that the job is considered skipped by looking in the UI for a failed build e.g. [here](https://github.com/pivotal-cf/tanzu-nodejs/runs/8229792500?check_suite_focus=true).
* If a job is considered `skipped`, then any PR checks that rely on it succeeding will actually pass. According to the [official Github actions documentation](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution):
> Note: A job that is skipped will report its status as "Success". It will not prevent a pull request from merging, even if it is a required check.
* To fix this …
=> Ensure that PR checks fail if integration test matrix fails.

stack/.github/workflows/create-release.yml
This PR fixes a couple of typos in the printing of the stack package diff. There is no functional change to the workflow - just fixing incorrect log/print statements.
Example current output (e.g. this [run](https://github.com/pivotal-cf/tanzu-jammy-tiny-stack/actions/runs/3064124951/jobs/4946989135)):
```
Build packages added: 0
Build packages modified: 0
Run packages added: 0
Run packages added: 0
Packages changed.
```
=> Fix typos in printing of stack package diffs.

actions/release/notes/entrypoint
Since we introduced the `--fail-with-body` flag to our actions, the release note action fails on the first release of a buildpack (as seen [here](https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime/actions/runs/3137370007)) due to no previous release being found. This specific step should not fail out if no release is found, as the release note code is already written to deal with that happening.
cc @paketo-buildpacks/dotnet-core-maintainers
=> Release note action: do not fail out if no release is found

actions/stack/create-stack/Dockerfile, actions/stack/create-stack/action.yml, actions/stack/create-stack/entrypoint
This PR adds a new action to create stacks. The behavior of this action is a superset of what currently exists in various workflows (create-release, test-pull-request, etc); it adds support for providing secrets.
In addition to providing new functionality, it also enables reduction of duplication of the existing logic in the existing workflows.
This PR intentionally does not update the workflows to use this action - that will come in a future PR once each workflow has been validated to work with this action.
This PR enables workflows to provide secrets when creating stacks, as well as reduces duplication of stack creation across workflows.
=> Add create-stack action.

stack/.github/workflows/create-release.yml, stack/.github/workflows/test-pull-request.yml
This PR leverages the `create-stack` action added in #560 instead of duplicating the logic for creating stacks.
This PR reduces duplication and allows the workflow to leverage features that are encapsulated within the action like support for secrets.
=> Use create stack action in create-release and test-pull-request.

builder/.github/workflows/synchronize-labels.yml, implementation/.github/workflows/synchronize-labels.yml, language-family/.github/workflows/synchronize-labels.yml, library/.github/workflows/synchronize-labels.yml, stack/.github/workflows/synchronize-labels.yml
Sometimes, a repo's labels drift from the desired sync'd values. This lets maintainers push a button to bring things back in line.
Also updates the `library` version of the workflow to be more similar to the other repo types' workflows.
=> Add manual trigger to label syncing on repos

stack/scripts/create.sh
This PR ensures that the create-stack script fails fast with a helpful error when the version of bash is less than v4.
Bash v4 was released in 2011, and so all modern linux operating systems run with at least this version of bash. Additionally, homebrew installs at least this version of bash.
The most likely situations where a user will encounter this is running on OSX with the default version of bash (which is still v3). Therefore it is reasonable to require these users to install a newer bash.
Resolves #576 - this provides useful, actionable, feedback to users if their bash is too old.
=> Fail fast with helpful error message when trying to create stack with old version of bash

stack/.github/workflows/push-image.yml
This PR publishes the Jammy stack run images to GCR as well as to Dockerhub.
Resolves #602
=> Publish jammy stack run images to GCR.

implementation/.github/labels.yml, implementation/.github/workflows/update-dependencies-from-metadata.yml
#592 
Tested that it gets triggered on a failure [here](https://github.com/paketo-buildpacks/passenger/actions/runs/3364505666), it only failed because the label wasn't available on the repo (it's been added in this PR).
I have high confidence that this will work when the label is available, since we're using an action we already use elsewhere.
=> Add workflow changes and label for dependency workflow failures

implementation/.github/workflows/update-dependencies-from-metadata.yml
Recent dependency update PRs have not been auto-approved by the paketo bot reviewer because [the dependency update commit is unsigned](https://github.com/paketo-buildpacks/dotnet-core-sdk/actions/runs/3421704329/jobs/5698207984#step:5:8). This adds the signing key information to the commit action so dependency update PRs can be auto-approved.
=> Add GPG key to dependency update commits

actions/release/find-asset/entrypoint
GitHub claims to always sort release by semver (descending) but we have seen situations where this is not the case. Therefore we should be explicit about sorting in the order we want when looking for release assets.
I did not find any other situations in this repo where we implicitly relied on the ordering of the `/repo/:full_name/releases` API endpoint.
Additional improvements:
- Improve debuggability by printing release version and asset filename for found asset.
- Exit with error when multiple assets are found.
Fixes #618 
It is hard to demonstrate the semver ordering, as I have only encountered issues on a private repo. But at least this shows the improved output from the happy-path:
```
❯ GITHUB_OUTPUT=/dev/null GITHUB_TOKEN=<token> ./actions/release/find-asset/entrypoint \
--repo …
```
=> Explictly sort by semver when finding release asset.

stack/.github/workflows/push-image.yml
This PR updates the stack image publishing step to push the build images for both Jammy and Bionic to Google Container Registry (GCR). This matches the existing behavior for run images, for both Jammy and Bionic.
In #603 we started to publish the run images for the Jammy stacks to Google Container Registry (GCR), to match the existing behavior of publishing the Bionic run images to GCR. However, we decided not to publish the build images to GCR because we weren't already publishing the Bionic build images.
It also pushes the Bionic build images to GCR under the legacy tag, for consistency with the Bionic run images.
GCR can be a better option for some consumers than dockerhub, so pushing stack images to both can improve user experience at minimal cost to us.
Closes #628
=> Publish stack build images to GCR.

implementation/.github/workflows/go-get-update.yml
As seen in failures like [this .NET buildpack](https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime/actions/runs/3457967590/jobs/5771914923), sometimes `go get -u all` fails to upgrade buildpack transitive dependencies. The problems seem to come from an issue with module version resolution. I've had a hard time tracking down a clear explanation of the difference between `go get -u all` and `go get -u -t ./...`. I do know that the latter works as expected consistently, doesn't upgrade dependencies to RC versions, and works for buildpacks that have a `main.go` (aka implementation buildpacks). I've seen all of the above issues with `go get -u all`. If someone can offer a good explanation of the difference - or make a good case for _not_ making this change, I'd be interested to …
=> Change method of upgrading implementation buildpack dependencies

implementation/.github/workflows/update-dependencies-from-metadata.yml
This PR removes an unnecessary job that was emitting a constant value for `go-version`.
Instead we hard-code the version of `go` to 1.18.x like we do everywhere else.
Reduces code complexity and maintenance burden, as well as performance issues relating to having additional jobs requiring additional VMs.
Closes #591
=> Remove unneccessary job in dependencies workflow.

builder/scripts/.util/tools.sh, implementation/.github/workflows/update-dependencies-from-metadata.yml, implementation/scripts/.util/tools.sh, language-family/scripts/.util/tools.sh, stack/scripts/.util/tools.sh
This PR ensures that all invocations of curl fail on error. See similar work in #554 (and #550) .
Workflows are guaranteed to run on jammy, so we can use the newer flags on those invocations. Other scripts might run with older versions of curl so only use the basic `--fail` flag.
This will help provide a more useful error when any of these curl invocations fail, rather than some more obscure downstream error.
See e.g. https://github.com/paketo-buildpacks/icu/issues/344
=> Ensure all instances of curl fail on error.

actions/stack/create-stack/entrypoint, stack/scripts/create.sh
The `--unbuffered` flag was deprecated in jam as it no longer has any function. We can safely remove it from all our invocations.
Closes #648
=> Remove --unbuffered flag from stack creation.

implementation/scripts/.util/builders.sh, language-family/scripts/.util/builders.sh
Now the Jammy is fully supported across the project, we should switch to using as our default for testing.
=> Switch to using Jammy as the default builder for integration testing

actions/issue/file/action.yml
Global node ID[1] of the issue can be used in subsequent jobs to perform an action on the created/edited issue.
E.g. add the issue to a project board etc.
gh cli does not yet have node-id support. So use gh graphql queries.
1: https://docs.github.com/en/graphql/guides/using-global-node-ids
=> issue file act: output node-id of created/mod issue

.github/workflows/update-tools.yml, builder/.github/workflows/approve-bot-pr.yml, builder/.github/workflows/push-image.yml, builder/.github/workflows/update-builder-toml.yml, builder/.github/workflows/update-github-config.yml, implementation/.github/workflows/approve-bot-pr.yml, implementation/.github/workflows/go-get-update.yml, implementation/.github/workflows/update-github-config.yml, language-family/.github/workflows/approve-bot-pr.yml, language-family/.github/workflows/update-buildpack-toml.yml, language-family/.github/workflows/update-github-config.yml, library/.github/workflows/approve-bot-pr.yml, library/.github/workflows/update-github-config.yml, stack/.github/workflows/approve-bot-pr.yml, stack/.github/workflows/update-github-config.yml
Add failure hooks for all workflows that do not have another mechanism for notification (e.g. a failed PR).
Opening issues for failed workflows will increase visibility and lower the effort required to identify failing workflows.
Closes #664
=> Add failure hooks for workflows.

actions/builder/update/action.yml, actions/buildpack/update/action.yml, actions/dependency/update-from-metadata/action.yml, actions/dependency/update/action.yml, actions/dependency/upload-to-s3/action.yml, actions/issue/file/action.yml, actions/pull-request/approve/entrypoint, actions/pull-request/auto-semver-label/check-files-changed.sh, actions/pull-request/check-human-commits/entrypoint, actions/pull-request/check-unverified-commits/entrypoint, actions/pull-request/checkout-branch/entrypoint, actions/pull-request/create-commit/entrypoint, actions/pull-request/merge/entrypoint, actions/pull-request/open/entrypoint, actions/pull-request/push-branch/entrypoint, actions/pull-request/rebase/entrypoint, actions/release/find-asset/entrypoint, actions/release/notes/entrypoint, actions/stack/create-stack/entrypoint, actions/stack/generate-package-list/action.yml, actions/sync/entrypoint, actions/tag/increment-tag/entrypoint, actions/tools/latest/entrypoint, builder/.github/workflows/create-release.yml
This change ensures that during execution of GitHub Actions, errors inside subshells/sub-commands are propagated to the caller. When coupled with `set -e` this ensures the scripts fail when they encounter a sub-shell error.
Without this change, errors in subshells are ignored and the scripts tend to fail later on in a less discoverable manner.
This change improves visibility of GitHub Actions faliures - ensuring failures are reported when they fail, rather than in a less discoverable manner later on
We can update all invocations that occur during GitHub actions because we config all of our actions to run on Ubuntu Jammy, which has a sufficiently recent version of Bash to support this command.
Do not modify scripts because they might be run outside of CI on older versions of Bash. In …
=> Ensure all actions exit on failure of sub-shell command.

implementation/.github/workflows/go-get-update.yml
The test dependencies are far more likely to have breaking changes and updating
them provides limited value to the buildpacks.
Fewer compilation failures to investigate and fix.
=> Do not update test dependencies with go get.

actions/tag/increment-tag/Dockerfile, actions/tag/increment-tag/entrypoint
In #669 we introduced `shopt` everywhere, but the `increment-tag` action was using `/bin/sh` instead of a recent version of `bash`. This PR fixes this action.
=> Fix broken tag action.

language-family/.github/workflows/create-release-issue.yml
File release reminder issue without unnecessary parentheses in the title:
`Week of (Feb 02): Cut buildpack releases` => `Week of Feb 02: Cut buildpack releases`
=> Remove unnecessary parentheses from release issue title

actions/sync/entrypoint
Make sure the target directory exists.
Example failure: https://github.com/paketo-buildpacks/occam/actions/runs/4080558752/jobs/7033137359
@ryanmoran I don't exactly know why you used the `"$(cd "${dir}" && pwd)/"` pattern. I guess this is to resolve any symlinks, right? So I think my `mkdir` should be fine.
BTW: The `src` dir does not need a `mkdir`, as we know it exists (we are looping over all src subdirs) 
If we add a new folder to the `github-config` repo, syncing will no longer work.
=> fix sync action fails on non-existing dir in target repo

implementation/.github/workflows/lint.yml, language-family/.github/workflows/lint.yml
Running golangci-linter on Go 1.19 is not supported until [1.48.0](https://github.com/golangci/golangci-lint/releases/tag/v1.48.0) meaning the latest update to Go 1.19 in our actions is causing the lint action to fail. I have updated to always pull the latest to hopefully avoid this in the future.
=> Makes golangci-linter version latest

actions/stack/release-notes/entrypoint/template.md
This is a follow-up to: https://github.com/paketo-buildpacks/github-config/pull/693
We do not want to print "No known CVEs" when CVE scanning itself is not performed.
e.g. https://github.com/paketo-buildpacks/jammy-full-stack/releases/tag/v0.0.70
=> stack/release-notes: avoid CVE section when scanning not done

builder/.github/labels.yml, builder/.github/workflows/update-builder-toml.yml, implementation/.github/labels.yml, implementation/.github/workflows/update-dependencies-from-metadata.yml, language-family/.github/labels.yml, library/.github/labels.yml, stack/.github/labels.yml
This PR ensures that the labels that are synchronized across the various
repositories are consistent with what the workflow failure-handlers expect.
Additionally:
* Ensure that the format of all failure labels is consistent (i.e. all failure
labels follow the pattern `failure:some-type`)
* Remove unused labels (e.g. library repositories do not have a push workflow
so the `failure:push` label is unneccessary).
Some of the failure hooks that open issues for workflow failures are themselves
failing because the repositories do not have the required labels.
=> Add workflow failure labels to synchronized labels

implementation/.github/workflows/label-pr.yml, language-family/.github/workflows/label-pr.yml, library/.github/workflows/label-pr.yml
According to the documentation, both major updates should not break us
Keep dependencies up-to-date
Also, the updated version of the action uses the new way of writing outputs ([see this blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)), but as we don't consume the output anywhere it probably doesn't matter. On the other hand, updating it makes it easier for me to track progress on the migration.
**UPDATE**
After reading the blog again, I guess it doesn't matter, if we use the output or not:
> Starting 1st June 2023 workflows using save-state or set-output commands via stdout **will fail with an error.**
=> Update `mheap/github-action-required-labels` to v3

builder/scripts/.util/tools.sh, builder/scripts/smoke.sh, implementation/scripts/.util/tools.sh, implementation/scripts/integration.sh, implementation/scripts/package.sh, language-family/scripts/.util/tools.sh, language-family/scripts/integration.sh, language-family/scripts/package.sh, stack/scripts/.util/tools.sh, stack/scripts/test.sh
This change only uses token if one is provided (and is non-empty). This results in backwards-compatibility for existing invocations that do not currently provide a token. It also means that human users do not have to provide a token to run these scripts.
Enable invocations of these scripts to use tokens if desired. This is in service of #653, as authenticated requests (i.e. using a token) have much higher rate limits and hence this change should help reduce flakiness in CI.
#653 will remain open even after this PR is merged as there are other instances where requests to GitHub are made without authentication.
This change does not modify the CI scripts to pass tokens - that change should come once these scripts are synced to downstream repos. We start with allowing the scripts to accept a …
=> Allow use of GitHub token when downloading assets (jam, pack, etc).

builder/.github/workflows/test-pull-request.yml, implementation/.github/workflows/test-pull-request.yml, language-family/.github/workflows/test-pull-request.yml, library/.github/workflows/test-pull-request.yml, stack/.github/workflows/test-pull-request.yml
According to their [release notes](https://github.com/actions/upload-artifact/releases/tag/v3.0.0) this is a major bump because:
> With the update to Node 16, all scripts will now be run with Node 16 rather than Node 12.
I guess this is only relevant, if you provide some custom code that runs in the context of the action.
Therefore the update should be safe.
Also: Some workflows already use v3.
Don't fall behind on dependencies
=> update the `actions/upload-artifact` from v2 to v3

builder/.github/workflows/lint-yaml.yml, implementation/.github/workflows/lint-yaml.yml, language-family/.github/workflows/lint-yaml.yml, library/.github/workflows/lint-yaml.yml
Update to the latest major version of `actions/setup-python`, which uses the new way of producing outputs in a github action as the old way is deprecated and will be removed (31st May 2023).
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
We already use it here: https://github.com/paketo-buildpacks/github-config/blob/0d8ff82ef5133a8e3d0f0b762ec1840d1c82a004/.github/workflows/lint-yaml.yml#L22 therefore I'm confident that the major version won't break us.
Keep the pipelines alive
=> update the `actions/setup-python` from v3 to v4

implementation/.github/workflows/go-get-update.yml
We don't want to cc this team. There isn't a single static team that covers all implementation buildpacks, so let's just delete the entire "cc" line.
=> Remove unused team cc from implementation go-get failure hook.

stack/.github/workflows/create-release.yml
This PR reduces the frequency of stack builds to once every 30 minutes instead of once every ten minutes.
The primary reason for this is because the full stack takes 10-20 mins to create the stack, which in turn results in GHA runs being skipped fairly frequently
More generally, this reduces load/contention on GHA and reduces the total number of flakes per day as there are fewer builds running. Waiting an extra 20 minutes for a new stack should be an acceptable trade-off for consumers.
=> Reduce frequency of stacks building to once per 30 mins.

.github/labels.yml, .github/workflows/synchronize-labels.yml, builder/.github/labels.yml, language-family/.github/labels.yml, library/.github/labels.yml, stack/.github/labels.yml
This PR adds the `help wanted` label (with the default color and description) to the various repositories. We have started using this label to indicate that we would like additional input, so we should ensure it is always available.
Additionally, this PR also adds labels (and the label-syncing workflow) to this repo itself.
=> Help wanted labels

builder/scripts/smoke.sh, implementation/scripts/integration.sh, language-family/scripts/integration.sh, stack/scripts/test.sh
This PR ensures that any Buildpacks that freezer builds during the tests (e.g. Java buildpacks, Watchexec, Procfile) are built with `CGO_ENABLED=0`. This is required for integration tests that use these Buildpacks to pass on the Bionic Stack/Builders.
Fixes issues like [this](https://github.com/paketo-buildpacks/poetry-run/actions/runs/4670505493/jobs/8270330347#step:5:270):
```
[detector] ======== Output: paketo-buildpacks/watchexec@2.8.1 ========
[detector] /cnb/buildpacks/paketo-buildpacks_watchexec/2.8.1/bin/detect: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /cnb/buildpacks/paketo-buildpacks_watchexec/2.8.1/bin/detect)
[detector] /cnb/buildpacks/paketo-buildpacks_watchexec/2.8.1/bin/detect: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not …
```
=> Run integration tests with CGO_ENABLED=0

actions/tools/latest/Dockerfile
Resolves #749 
We recently started seeing this workflow fail on the `actions/tools/latest` action step for updating `jam` with `curl: (48) An unknown option was passed in to libcurl`. Installing `curl-dev` resolves this error, although I'm not entirely sure _why_ this issue cropped up in the first place.
=> install curl-dev in tool update action

language-family/.github/workflows/create-release-issue.yml
This PR changes the day that release issues are filed to Monday (from Wednesday) and moves the time earlier. This way the stories will exist by the time team members start their work for the week
=> File language family issues on Monday not Wednesday

builder/scripts/.util/tools.sh, implementation/scripts/.util/tools.sh, language-family/scripts/.util/tools.sh, stack/scripts/.util/tools.sh
Currently, the tools that are used by various dependent projects assume `amd64` architecture even on `arm64` machines. These tools don't work on all `arm64` machines so we should use architecture specific versions of these tools when building stacks and buildpacks. Resolves #756
The automation to build stacks and buildpacks should use architecture specific tools when running on `arm64` and `amd64` machines.
=> Use os/architecture specific tools, dealing with varying tool artifact naming conventions

actions/release/find-asset/entrypoint
The action `actions/release/find-asset/entrypoint` retrieves all the releases with the GitHub API but it does not take into account cases in which pagination is activated (number of releases greater than 100) and therefore generates errors when obtaining them.
For the specific case of [Jammy Full Stack](https://github.com/paketo-buildpacks/jammy-full-stack), there are 101 releases in total, so the result of the command is something like this:
```json
[
{"tag": "v0.0.2"}
{"tag": "v0.0.3"}
{"tag": "v0.0.4"}
.
.
.
{"tag": "v0.0.101"}
]
[
{"tag": "v0.0.1"}
]
```
Note that the results are 2 sets of JSON arrays. With the proposed change, It will merge the JSON arrays  from the GitHub API response using `jq` into a single JSON.
Fix https://github.com/paketo-buildpacks/jammy-full-stack/issues/14
=> Add pagination handling for find-asset action

stack/.github/workflows/create-release.yml, stack/scripts/receipts.sh
Use the word "image" for the build/run OCI file as has been used widely in this shared github-config.
Archive is also used for filesystem tar archives produces by the likes of "docker export". This change avoids the chance of confusion
And, remove an unused variable
=> stack: use consistent language: s/archive/image

actions/release/find-asset/entrypoint
Don't slice off the first character from every tag. It's true the all current buildpack/stack repos use tags of format "vX.Y.Z" but this change will make it usable for repos that just use "X.Y.Z"
=> action/find-asset: slice off first char only if it's a "v"

implementation/.github/workflows/create-draft-release.yml, implementation/.github/workflows/test-pull-request.yml, language-family/.github/workflows/create-draft-release.yml, language-family/.github/workflows/test-pull-request.yml
It's observed that pack uses /tmp as its default temp dir which on github runners may not have sufficient memory (leading to "no space on disk" errors). So explicitly tell pack to use the github runner's assigned tmpdir
=> int tests: set TMPDIR to github runner's tempdir

implementation/scripts/integration.sh, language-family/scripts/integration.sh
Some of the tests (e.g. stack upgrade) will explicitly pull and remove images for other builders, which means by the time the next test runs the pre-pulled images for that other builder have been removed.
By pulling builder images (including the lifecycle and run image) just before the specific test runs, we guarantee that the necessary images are present.
Tests pass when run serially (e.g. locally) across builders for different stacks.
=> Pull builder images just before running integration tests.

actions/sync/entrypoint
This PR adds support for arbitrary behavior after syncing via a `.github/.sync-post-hook` file. If the file exists, it is executed after the syncing process. If the file does not exist, the action does not attempt to execute it.
I have tested this locally - and it works as described above - but it's a lot of work to demonstrate this working in a CI environment so I'd like to merge this without needing to set up branches on an example repository to show the functionality.
This provides a simple yet powerful mechanism to make repository-specific changes to files that are synced from the common/shared location. A good example of this is running `ytt` to make changes to a workflow file that should only exist for some repositories (e.g. running on a custom/self-hosted runner).
It could also …
=> Run post-sync hook if it exists during sync action.

actions/release/find-asset/entrypoint
This PR fixes some accidentally broken behavior in the `find-asset` action. This script/action should exit without error when no asset is found and 'strict' is set to 'false'.
When bootstrapping a new repository we need to be able to succeed without any existing releases (and hence no release assets).
=> Fix release find-asset action

actions/release/find-asset/entrypoint
=> Fix typo in find-asset action

builder/.github/dependabot.yml, implementation/.github/dependabot.yml, language-family/.github/dependabot.yml
Follow up to #813, add config for Dependabot to pick up transitive go.mod dependencies instead
Tested in Bundler and it worked well:
https://github.com/paketo-buildpacks/bundler/pull/566
https://github.com/paketo-buildpacks/bundler/pull/565
https://github.com/paketo-buildpacks/bundler/pull/564
https://github.com/paketo-buildpacks/bundler/pull/563
https://github.com/paketo-buildpacks/bundler/pull/562
https://github.com/paketo-buildpacks/bundler/pull/561
=> dependabot: pick up transitive (indirect) dependencies

builder/.github/dependabot.yml, implementation/.github/dependabot.yml, language-family/.github/dependabot.yml
We just introduced transitive dependency bumping via Dependabot but it ss very noisy. To reduce the number of PRs, this change will hopefully  group the patch/minor Dependabot changes together in 1 PR to reduce noise
=> Dependabot config: group patch/minor bumps together

builder/.github/workflows/approve-bot-pr.yml, implementation/.github/workflows/approve-bot-pr.yml, language-family/.github/workflows/approve-bot-pr.yml, stack/.github/workflows/approve-bot-pr.yml
Remove failure notifications when PR bot approvals fail. We're getting blown up with these notifications, and we came to a consensus that these failures are not necessary to be notified about.
Failures are due to flakiness in PR artifact upload, which cause the zip file we download in the bot approval workflows to be corrupted. This is a well-documented issue on the github-provided upstream Upload Artifact action. We can look into changing how we do automated PR approvals in a separate issue.
=> Remove bot approval workflow failure notifications

.github/workflows/update-tools.yml, builder/.github/workflows/update-builder-toml.yml, builder/.github/workflows/update-github-config.yml, implementation/.github/workflows/codeql-analysis.yml, implementation/.github/workflows/update-dependencies-from-metadata.yml, implementation/.github/workflows/update-github-config.yml, language-family/.github/workflows/create-release-issue.yml, language-family/.github/workflows/update-buildpack-toml.yml, language-family/.github/workflows/update-github-config.yml, library/.github/workflows/codeql-analysis.yml, library/.github/workflows/update-github-config.yml, stack/.github/workflows/create-release.yml, stack/.github/workflows/update-github-config.yml
This PR separates the cron schedules for the various workflows. They were generated with psuedo-random number generators.
In most cases the overal frequency is unchanged, but in some cases (like stacks) the frequency is reduced substantially.
We are starting to see issues with hitting GitHub API rate limits as well as workflow runs having infrastructure issues, and this is a quick and easy step to reduce the number of workflows running at the same time.
=> Separate cron schedules for recurring workflows

.github/.yamllint
This PR removes a `yamllint` check requiring a minimum number of spaces between the `#` and the start of the comment.
We do not find this lint check improves readability and we consistently forget to adhere to it.
=> Relax yamllint comment space constraint.

actions/tag/increment-tag/entrypoint
This PR improves the debug output for the "increment tag" action.
We recently ran into an issue where the output tag was not what we expected (see [this failing build](https://github.com/paketo-buildpacks/jammy-base-stack/actions/runs/6536023435/job/17746971933)). This PR improves the debug output so it is easier to reason about which logic path is being taken.
As a side note, I switched to `git tag --merged` (from `git rev-list --tags --max-count=1`) because it allows us to get a list of tags, not just the most recent one. This has the side effect of only listing tags that are in the current branch. This is probably what we want, as we should probably not include tags that aren't on the current branch, but I wanted to call it out explicitly.
=> Improve debug output for increment tag action.

implementation/scripts/integration.sh
This source is causing the integration script to fail https://github.com/paketo-buildpacks/go-dist/actions/runs/6799026441/job/18484652568?pr=666
=> Remove source of non-existent .util/git.sh file

.github/.yamllint
Formatting a workflow with `yq` produces YAML blocks in some cases that cause linting failures when `indent-sequences: consistent` is set in the configuration. I think we should allow valid yq-formatted YAML to pass out linter checks so various tools aren't at odds
Example: ` yq implementation/.github/dependabot.yml` produces YAML that currently FAILs linting with:
```
.github/dependabot.yml
10:5      error    wrong indentation: expected 2 but found 4  (indentation)
15:9      error    wrong indentation: expected 6 but found 8  (indentation)
17:9      error    wrong indentation: expected 6 but found 8  (indentation)
```
=> yamllint config: relax indentation consistency

actions/sync/entrypoint
This PR adds the `sync-post-hook` file to the included list of files that are synced from the shared config to downstream repositories. Specifically, it removes the exception where it _was not_ included, and therefore the `sync-post-hook` file is now treated the same as any other file.
This change allows us to put common post-hook scripts in the shared config and propagate them to down repositories like any other file. If a repo wants a specific post-hook script that differs from the shared one (or one where the is none in the shared config repo), it can be added to the `.syncignore` file like any other ignored file.
=> Include the post-hook sync script in the list of synced files.

builder/.github/workflows/push-image.yml
This PR adds functionality for generating Dockerhub org variable based on the repository owner name. E.x. instead of having `DOCKERHUB_ORG` env variable pinned to value `paketobuildpacks` we fetch the repository owner `paketo-buildpacks` or `paketo-community` and we remove the `-` to match the dockerhub org name. This change is helpful as repositories under the paketo-community organization can now sync the `push-image.yml` file
=> Generating dockerhub org name according to github repo owner

builder/.github/workflows/push-image.yml, builder/scripts/.util/tools.sh, implementation/scripts/.util/tools.sh, stack/scripts/.util/tools.sh
This PR adds enables the experimental feature during the installation of pack. This is possible by looking at the `options.json` file under the `./scripts` directory. If someone wants to enable experimental features in pack, needs to create an `options.json` file with below content
```json
{
"pack_config_enable_experimental": true
}
```
In case there is no `options.json` file available, it fallbacks to the old behavior which is not enabling experimental features of pack.
This PR gives the option to specify if the script should enable or not the experimental features of `pack`.
=> Adding option for enabling experimental options in pack

stack/.github/workflows/push-image.yml
On this PR, we refactor the implementation of push-image.yml file for the stacks. This refactor has below benefits:
* Agnostic to whether the stack has 2 or 2*x images as there are no hardcoded values (extension support).
* Enables Github action concurrency, as a result less time for the actions to complete
* Reduces the amount of code 
* With few changes in the future, it can easily support the Targets concept.
This PR has been Tested on jammy-base-stack and ubi-base-stack.
* Both buildpack and extension support
=> Code reusability on pushing stack images to registry

implementation/.github/dependabot.yml, language-family/.github/dependabot.yml
Adds a few of the frequently problematic go modules to an exclude-pattern, meaning they won't be updated in Dependabot group PRs, but instead will go into their own PRs which will help unblock us updating other updates in the instance of incompatibilities
Followed these docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#example-1
=> Dependabot: exclude problematic dependencies from group PRs

stack/.github/workflows/push-image.yml
This PR fixes the failure that occurs during the execution of the push-image workflow. Specifically, the dynamic fetching of the registry name while pushing to GCR was wrong.
=> fixing GCR name

actions/update-go-mod-version/Dockerfile, actions/update-go-mod-version/action.yml, actions/update-go-mod-version/entrypoint, builder/.github/workflows/update-go-mod-version.yml, implementation/.github/workflows/update-go-mod-version.yml, language-family/.github/workflows/update-go-mod-version.yml, library/.github/workflows/update-go-mod-version.yml, stack/.github/workflows/update-go-mod-version.yml
This PR adds a workflow to update the version of `go` and the `toolchain` in `go.mod`. It also adds the associated failure labels for when this job fails.
See https://github.com/orgs/paketo-buildpacks/discussions/283
We want to keep the `toolchain go1.X.Y` line up to date with the latest version of go available, as that is the actual version of the `go` toolchain that will be used to build the module. If this line is present, `go` will guarantee to build with this version of `go` toolchain, regardless of what version is provided in CI. Essentially this line locks down the version of go used to build a module at a specific point in time. By keeping it up to date, we guarantee that we're always building with the latest version of `go`.
One caveat is that this `toolchain` line _requires_ a …
=> Add workflow to update go mod version.

actions/update-go-mod-version/entrypoint
This PR fixes a bug in in the action that updates the version of go.
Specifically:
The `sort -C/--check=silent` option only exists on GNU sort, but the action runs busybox sort (as it is on alpine). There is no equivalent for the `-C` for the version of `sort` we are using, so we have to implement something else.
I've validated this works against real `go.mod` files.
=> Fix go mod update workflow

actions/pull-request/open/entrypoint
- we often see this action fail with graphQL errors if we try to open too many PRs in a short amount of time.
I've validated this logic works locally:
```
❯ docker run --rm -it -e GITHUB_WORKSPACE=. -e GITHUB_REPOSITORY="<some-repo>" gha-pr-tmp --token "$(gh auth token)" --branch 'tmp' --title 'whatever' --body '' --base 'missing-branch' --label 'some-label'
A new release of gh is available: 1.7.0 → v2.50.0
https://github.com/cli/cli/releases/tag/v2.50.0
Opening Pull Request
running command: gh pr create --title test PR --body test pr body --base bad --label some-label
fatal: not a git repository (or any of the parent directories): .git
/usr/bin/git: exit status 128
Failed to run command. Retrying in 1 seconds...
...
/usr/bin/git: exit status 128
Failed to run command. Retrying in 32 …
```
=> Add exponential backoff to open-pr action.

actions/pull-request/checkout-branch/action.yml, actions/pull-request/checkout-branch/entrypoint, actions/pull-request/push-branch/action.yml, actions/pull-request/push-branch/entrypoint
This PR adds support for force pushing the branches from a specific location when using the Pull Request branch push action.
This is useful because there are situations where automation checks out a branch but for whatever reason fails to create a PR (or the PR is later closed). This PR allows a workflow to check out the branch at a specific location, regardless of where the upstream is at, and then force push that branch. This would have the forcing function of also opening a new PR for this branch once it is force-pushed.
When used in a github workflow like `sync-github-config` with `start-point: HEAD`, this will have the effect of squashing all outstanding changes into a single commit that is then rebased on top of `HEAD`, and force-pushing this to the upstream location.
When there are …
=> allow checkout force pr

actions/pull-request/auto-semver-label/check-files-changed.sh
The function of this task is to check if it can auto-label anything with a semver label and return the label if it can. It is run after a check to see if there are any semver labels already set and if there are not this action will run. I think that it would then follow logically that this action should fail if there are no labels to add meaning the whole check task will fail.
=> Make auto-label semver action fail if there are no patchfiles

actions/release/publish-drafts/entrypoint
Fixes an edge case in the publish-drafts action:
Old behaviour, resulting in occasional wrong sort order:
```
gh api /repos/<REPO>/releases | jq -r '[.[] | select(.draft == true) | .tag_name] | sort'
[
"v0.10.2",
"v0.5.14",
"v0.7.11",
"v0.8.13",
"v0.9.9"
]
```
New behaviour:
```
‣ gh api /repos/<REPO>/releases | jq -r '[.[] | select(.draft == true) | .tag_name] | map(ltrimstr("v")) | sort_by( split(".") | map(tonumber) )'
[
"0.5.14",
"0.7.11",
"0.8.13",
"0.9.9",
"0.10.2"
]
```
=> Publish-drafts action: fix edge case

actions/release/publish-drafts/entrypoint
Fixes bug we saw in publishing draft releases ([example](https://github.com/paketo-buildpacks/bundler/actions/runs/9477130331/job/26111171035)), in which no releases went out because the `v` version prefix had been trimmed off the tag versions for sorting, and then we never re-added them.
I have tested this locally end to end and seen this work successfully now. Sorry for the noise!
=> publish drafts bug fix: re-add v version prefix

actions/tag/calculate-semver/entrypoint/main.go, actions/tag/calculate-semver/entrypoint/main_test.go
There is a possibility that a non-merged PR can be listed on a commit this will cause this action to fail if that non-merged PR does not have an image label. This makes it so that still open PRs are not considered.
=> Only considers PRs that have been merged it listed on a commit

implementation/scripts/package.sh
This PR changes the package.sh script to conditionally package a buildpack or an extension according to whether is an extension or a buildpack.
The way this is implemented is to check whether the extension file exists on the directory, otherwise, it fallbacks to the default behavior of packaging a buildpack.
Test results:
* node-engine: https://github.com/pacostas/node-engine/pull/48
* ubi-nodejs-extension: https://github.com/pacostas/ubi-nodejs-extension/pull/67
=> Conditionally packaging a buildpack or an extension

actions/stack/release-notes/action.yml, actions/stack/release-notes/entrypoint/main.go, actions/stack/release-notes/entrypoint/template.md
This PR adds an option called `receipts-show-limit` where in case the limit, which corresponds to the number of items of the array for each removed, build or added, has been exceeded, then it hides the receipts by replacing them with the message `❌ TOO large to include` 
E.g if we set the limit to 0 it will show below readme file
```markdown
Build: `build_image_url`
Run: `run_image_url`
No USNs patched in this release.
```
❌ TOO large to include
```
```
❌ TOO large to include
```
```
❌ TOO large to include
```
```
❌ TOO large to include
```
```
❌ TOO large to include
```
```
❌ TOO large to include
```
```
Instead of below one. 
```markdown
Build: `build_image_url`
Run: `run_image_url`
```
liba-dev 2.22.2-222.222 (PURL: pkg:purl/purl/linux)
```
```
liba-dev 1.11.1-111.111 ==> …
=> Limit show receipts

stack/.github/workflows/create-release.yml, stack/.github/workflows/test-pull-request.yml
- The version of skopeo that runs on ubunut 22.04 is too old for the version of docker now installed on github action runners.
- it is very hard to update skopeo on the runners - they just install whatever is available upstream by ubuntu (and skopeo does not publish pre-built binaries)
- our options are either compile from source every time we need skopeo (ineffient and brittle), manually install skopeo from a third-party ppk (also somewhat slow and sketchy) or use a runner with a newer version of ubuntu and hence skopeo (fastest, least brittle).
- we update every instance of a runner in the workflows that use skopeo against the local daemon to avoid any potential issues that might occur when hopping between runner versions during workflow execution.
=> Run stack test workflows on ubuntu 24.04

actions/buildpack/update/action.yml
This PR adds support for outputting the semver version when bumping the buildpack. It utilizes the newly added semver output in `jam` ([jam PR](https://github.com/paketo-buildpacks/jam/pull/343/files))
~~Technically this will break if used against an older version of `jam`. I could guard against that, but I'd rather use the broken builds as a forcing function to ensure that we keep `jam` up to date everywhere. This is similar to what we did when adding the `--patch-only` to this action - we expect it to run against a newer version of `jam`.~~
Turns out this _won't_ break against an older version of `jam` - it will just emit an empty string for the semver bump. We can guard against this in the workflow (i.e. don't attempt to add a blank `semver:` label). We would probably want to do this …
=> Output semver bump from buildpack update action.

actions/release/notes/action.yml, actions/release/notes/entrypoint
This PR adds an extra argument called `--buildpack-type` on the `paketo-buildpacks/github-config/actions/release/notes` action. That way, we can specify for which type of buildpack (buildpack or extension) the release notes should be generated.
=> Release notes: option for specifying on summarize whether is a buildpack or an extension

implementation/.github/workflows/push-buildpackage.yml
This PR adds an extra option, which specifies on which registry the implementation should push. Specifically, if on the root directory of the implementation, there is a file called `registries.json` with the below content
```
{
"dockerhub": true,
"GCR": false
}
``` 
it means that the action will push the image to `dockerhub` but NOT to `GCR`. 
In case the `registries.json` file does not exist, it fallbacks to the current behavior which is to push on both registries.
In case where an attribute is NOT specified, then the default value is `true`.
This is useful for projects being under paketo-community organization, where GCR is not available.
=> Conditionally selecting on which registry to push

stack/.github/workflows/push-image.yml
This PR adds an extra option, which specifies on which registries the stack should push. Specifically, if on the root directory of the implementation, there is a file called `registries.json` with the below content
```
{
"dockerhub": true,
"GCR": false
}
``` 
it means that the action will push the stack images to `dockerhub` but NOT to `GCR`. 
In case the `registries.json` file does not exist, it fallbacks to the current behavior which is to push on both registries.
In case where an attribute is NOT specified, then the default value is `true`.
This is useful for projects being under paketo-community organization, where GCR is not available.
=> Stack - Select on which registries to push stack images

stack/scripts/.util/tools.sh, stack/scripts/test.sh
* I missed closing a curly bracket on `test.sh` script and therefore, below PRs on syncing the changes for the registry are failing.
* https://github.com/paketo-buildpacks/jammy-static-stack/actions/runs/9771547170/job/26974452884?pr=131
* https://github.com/paketo-buildpacks/jammy-tiny-stack/actions/runs/9771583535/job/26974548101?pr=159
* https://github.com/paketo-buildpacks/jammy-base-stack/pull/153
* Added logging the `crane` version, in case it is already installed, similar to what other tools do.
* Changed the `util::print::title` to `util::print::info` for `skopeo` to be consistent with what the other tools log.
=> Fixing syntax error on stack test.sh scripts

implementation/.github/workflows/push-buildpackage.yml
On this step https://github.com/paketo-buildpacks/github-config/blob/ed11d20621aa11f7fbf6c2c29dbd3bcc7efebb56/implementation/.github/workflows/push-buildpackage.yml#L100 the image and digest are being used from the previous step. Due to previous step does not have an id, the value of both variables is empty.
This PR adds back the id on the push to dockerhub step
=> Adding back the id on push to dockerhub action

actions/update-go-mod-version/action.yml, actions/update-go-mod-version/entrypoint, builder/.github/workflows/update-go-mod-version.yml, implementation/.github/workflows/update-go-mod-version.yml, language-family/.github/workflows/update-go-mod-version.yml, library/.github/workflows/update-go-mod-version.yml, stack/.github/workflows/update-go-mod-version.yml
This PR changes the behavior of the action that updates the go toolchain version to also update the `go` version in addition to updating the `toolchain` version. This is necessary because some of our dependencies have higher versions of go than we do and in order to keep them up to date we must also bump to the minimum version of go that they have. Rather than trying to identify the lowest-common-denominator across all dependencies it is easier to always use the latest version.
If we wanted to ensure that we did not need the latest version of go, we could choose to not bump these dependencies. But I think we should keep our dependencies up to date and accept the golang bump. Especially because most of our products are binaries and not libraries, and hence we can control the version of …
=> Update go version as well as toolchain version.

actions/update-go-mod-version/entrypoint
- running go mod tidy removes the toolchain version when it is identical to the go version (which it will always be).
- also fix a bug in the regex which was inadvertently bumping packages as well as the go version itself.
=> Only update the go version in go.mod update action.

language-family/.github/workflows/publish-releases.yml
- only manual dispatch for now until we are comfortable auto-publishing language family buildpacks.
=> Add language family workflow to publish all releases.

.github/workflows/update-tools.yml
This PR fixes the failure on updating stack tools due to crane `ENV` variable is missing.
* https://github.com/paketo-buildpacks/github-config/actions/runs/10762619641/job/29843175151
=> Fixing error on update stack tools by adding crane missing argument

builder/.github/workflows/test-pull-request.yml, implementation/.github/workflows/test-pull-request.yml, implementation/.github/workflows/update-dependencies-from-metadata.yml, language-family/.github/workflows/test-pull-request.yml, library/.github/workflows/test-pull-request.yml, stack/.github/workflows/create-release.yml, stack/.github/workflows/test-pull-request.yml
See the thread: https://paketobuildpacks.slack.com/archives/C011S6EL49L/p1732109132421729
The v3 branches of both of these actions are browned out and we need to upgrade to v4.
=> Upgrades upload and download artifact actions

stack/.github/workflows/create-release.yml
- Removed test that only check the status of output variables in favor of using those variables outright this should reduce our overhead by reducing the number of VMs we need to acquire
- Collapse evaluating jobs into a higher level job to both reduce overhead as well as reduce file passing in the case of package diffing
=> Refactor workflow and pass diff files correctly

implementation/scripts/.util/tools.sh
Removed unnecessary intermediary file for `pack` installation `/tmp/pack.tgz`
The file is completely unnecessary since pipe can be used.
What's more important: the temp file has fixed name thus creating datarace.
If anything the names should be unique for each invocation for instance by using `mktemp`.
This enables parallel build for multiple buildpacks at the same time on the same machine.
Obviously it would be best if each build did not install `pack` for itself all over again...
=> Remove unnecessary tmp file

library/.github/workflows/update-go-mod-version.yml
Updating the Go version fails for repositories using the action in the library path. Examples:
- https://github.com/paketo-buildpacks/packit/actions/workflows/update-go-mod-version.yml
- https://github.com/paketo-buildpacks/packit/actions/workflows/update-go-mod-version.yml
This PR aligns the branch which is checked out initially (L 20) with the one that is pushed (L 66, 74).
=> Fix branch name for updating Go version for libraries

actions/stack/generate-package-list/action.yml
This PR adds the option of storing the output of the action to a file instead of storing it to a variable. This is useful in case the output is more than what the github action terminal can handle, where in that case it will fail.
=> adding capability of outputing packages into a file

actions/stack/get-usns/action.yml, actions/stack/get-usns/entrypoint/go.mod, actions/stack/get-usns/entrypoint/main.go
This PR does below things:
1. Adds noble on the regex expressions to properly scrap the usns from ubuntu page
2. Removes the default value from distribution, as it is better to error in case the user has not specified an ubuntu distribution compared to having a false fallback.
3. Upgrades `io/util` to `io`, as `io/util` is deprecated
4. Adds an extra flag called `packages_filepath` which is similar to packages and it enables passing the data through file. This is usefull in case there are a lot of packages, where in that case the workflow will fail due to terminal has a limit.
=> stack/get-usns general fixes/upgrades

implementation/.github/workflows/push-buildpackage.yml
This PR disables the default functionality from pushing buildpack images to GCR
=> Disable pushing buildpacks to GCR

stack/.github/workflows/push-image.yml
This PR sets as default for the push-image workflow on the stacks, to stop pushing to GCR.
=> Stack: Disable pushing to GCR

actions/stack/get-usns/action.yml, actions/stack/get-usns/entrypoint/main.go
This PR:
* Introduces a new flag called `--output` which specifies in which filepath to store the usns instead of outputing them on a variable.
* Removes logging the usns on the console.
That way we avoid hitting the `Argument list too long` error while running this action on a github workflow, when the usns list is too long.
=> Introducing --output flag on get-usns action.

actions/stack/get-usns/action.yml, actions/stack/get-usns/entrypoint/main.go
This PR adds a new flag on the get-usns action called `last_usns_filepath` which enables the action to read the last usns from a file instead of a variable
It has been tested here https://github.com/pacostas/jammy-base-stack/actions/runs/14666445319/job/41162655763
=> Get last usns from a filepath

language-family/.github/workflows/push-buildpackage.yml
This PR enhances the push image workflow by adding the capability to conditionally push to the GCR registry. This push will only occur if the registries.json file is present and its GCR attribute is set to true.
This change has been tested for the past months on the implementation buildpacks.
=> fix: conditionaly pushing to GCR

.github/renovate-config.js, .github/workflows/renovate.yml
User "Renovate Bot" is not configured to comply with Linux CLA. Instead, user "paketo-bot" should open PRs and subscribe commits for dependency updates.
=> Change Renovate users

actions/release/find-asset/entrypoint
jq 1.8 made a change to the `limit()` function, passing -1 to n is not allowed anymore. See https://github.com/jqlang/jq/blob/jq-1.7.1/src/builtin.jq#L149-L152 vs https://github.com/jqlang/jq/blob/jq-1.8.0/src/builtin.jq#L142-L145
This PR changes the `find_asset()` function to omit the call `limit`.
Tried it out:
```sh
$ GITHUB_OUTPUT=/tmp/out ./entrypoint --repo paketo-buildpacks/jammy-full-stack --pattern '\d+.\d+(.\d+)?-patched-usns.json' --depth 10 --strict false
github.com
✓ Logged in to github.com account SaschaSchwarze0 (GITHUB_TOKEN)
[...]
Found asset: 'jammy-full-stack-0.1.90-patched-usns.json' on repo: 'paketo-buildpacks/jammy-full-stack' version: 'v0.1.90'.
Asset URL: https://api.github.com/repos/paketo-buildpacks/jammy-full-stack/releases/assets/270918610 …
```
=> Handle depth -1 because jq-1.8 does not anymore support -1 on limit()

implementation/.github/workflows/push-buildpackage.yml
Replaced 'skopeo' with 'crane' for digest inspection.
This PR fixes the issue with not fetching the index digest for compaing the .sha  https://github.com/paketo-buildpacks/conda-env-update/actions/runs/17445240326/job/49537953476
The fix has been tested here https://github.com/pacostas/conda-env-update/actions/runs/17499919107/job/49710140198
=> fix: replacing skopeo with crane to fetch digest

language-family/scripts/package.sh
This change is needed to allow the release-notes workflows to work for multi-arch buildpacks
Fixes this failure
https://github.com/paketo-buildpacks/python/actions/runs/17674771840/job/50234652780
Tested here
https://github.com/jericop/python/actions/runs/17744944908
=> Copy linux-amd64 cnb archive to buildpackage.cnb for multi-arch

implementation/scripts/publish.sh
This fixes an issue with the publish script that prevents it from working on mac. The variable should not be an array and this fixes it so it works on mac and linux.
Allow for local testing. Verified the change locally.
=> Switch from array to scalar for image_ref in publish.sh

builder/.github/workflows/create-release.yml, builder/.github/workflows/push-image.yml, builder/.github/workflows/update-builder-toml.yml, builder/scripts/.syncignore, builder/scripts/options.json, builder/scripts/publish.sh, builder/scripts/smoke.sh
This PR:
* Enables builders to support multiple architectures 
* Enables builders to support producing multiple images based on the description of the RFC https://github.com/paketo-buildpacks/rfcs/blob/b550e96431755d7e94b0dcb4ac2d98aa73c90c23/text/0061-core-builder.md
* Alters the output of the release notes to include only the builder names that are published to the registry and adding the  information of the builder as an asset, in case the builder is more than one. Example of a release output: https://github.com/pacostas/builder-jammy-buildpackless-base/releases/tag/v0.1.0 
* It supports backward compatibility, so it will not break any builder workflows
Create release workflow has been tested here https://github.com/pacostas/builder-jammy-buildpackless-base/actions/runs/17878694540 …
=> Multi-arch and multi-image support for builders
